import type { Question } from "./types";

type DistractorTexts = readonly [string, string, string, string, string];
type CorrectTexts = Readonly<{ primary: string; alternate: string }>;

const correctTextOverrides: Partial<Record<string, CorrectTexts>> = {
  "l1-network-status-codes": {
    primary: "HTTP 404は、requestで指定されたresourceをserverが見つけられなかったことを表す",
    alternate: "URLやresource IDに対応する対象が存在しない場合に返すNot Foundのstatus code",
  },
  "l1-design-yagni": {
    primary: "将来必要になるという予測だけでは作らず、実際に要件となった時点で実装する考え方",
    alternate: "未確定の拡張を先回りして複雑さを増やさず、現在必要な機能へ設計を絞る原則",
  },
  "l1-security-https-certificate": {
    primary: "信頼するCAの署名でdomain名と公開鍵の結び付きを検証し、clientが接続先serverを認証する",
    alternate:
      "証明書chainとhost名を確認してなりすましを防ぎ、公開鍵でTLS handshake中のserver署名を検証する",
  },
  "l1-security-vulnerability-patch": {
    primary: "攻撃者がsecurity上の目的に悪用できる、softwareの設計・実装・設定にある弱点",
    alternate: "機密性・完全性・可用性などを損なう攻撃経路になり得るsystem上の欠陥",
  },
  "l2-network-nat": {
    primary:
      "private IPとglobal IP・portの対応をrouterが変換し、内部端末から外部networkへ通信させる仕組み",
    alternate:
      "複数の内部hostによる通信を一つのpublic IPへ対応づけ、戻りのpacketを元のhostへ振り分ける仕組み",
  },
  "l2-network-port-number": {
    primary:
      "IP addressでhostを選んだ後、そのhost内で通信を受け取るapplicationやserviceを識別する番号",
    alternate: "TCPやUDPで同じmachine上の複数processを区別し、packetの配送先socketを決める番号",
  },
  "l2-network-http-acronyms": {
    primary:
      "HTTPはhypertext転送、TLSはtransport通信の保護、DNSはdomain名の解決を担うprotocolやsystem",
    alternate: "HTTPはrequest/response、TLSは暗号化と相手確認、DNSはhost名と接続先の対応づけを担う",
  },
  "l3-network-websocket": {
    primary:
      "一度確立したconnectionを維持し、clientとserverの双方から任意のtimingでmessageを送れる",
    alternate:
      "HTTPからupgradeした一本のconnection上で、request/responseに限定されない双方向通信を続ける",
  },
  "l3-design-acid": {
    primary: "Atomicity・Consistency・Isolation・Durabilityというtransactionの四つの性質を表す",
    alternate: "全成功か全失敗、一貫した制約、並行実行の分離、commit後の永続性をまとめた性質",
  },
  "l4-design-slo-sli": {
    primary: "SLIはlatencyや成功率などの実測指標、SLOはその指標について達成を目指す水準",
    alternate: "観測する信頼性metricがSLIで、一定期間に守る目標値を定めたものがSLO",
  },
  "l5-design-backpressure": {
    primary:
      "consumerの処理能力を超えた流入に対し、producerへ待機や送信rate低下を伝えて滞留を抑える仕組み",
    alternate:
      "下流のqueueやbufferの余力を上流へfeedbackし、生成速度を受け入れ可能な量へ調整する制御",
  },
  "l5-security-cors-misconfig": {
    primary:
      "requestのOriginを検証せずそのまま許可しcredentialsも有効にすると、攻撃siteから認証済みresponseを読まれ得る",
    alternate:
      "信頼originの判定が緩い状態でcredential付きcross-origin readを許すと、被害者の権限で取得したdataが漏れる",
  },
  "l6-network-congestion-control-algorithms": {
    primary:
      "BBRはbottleneck bandwidthとRTTを推定し、loss発生そのものよりnetwork modelを基に送信量を調整する",
    alternate:
      "CUBICが主にlossを輻輳signalとするのに対し、BBRは推定帯域と最小RTTからpacingとinflight量を決める",
  },
  "l7-computer-lock-free": {
    primary:
      "期待値との一致を確認した場合だけ一つの値をatomicに更新し、競合を検出しながらlockなしの状態遷移を組み立てる",
    alternate:
      "compareとswapを不可分に行い、他threadが値を変えていなかったときだけ更新を成立させるread-modify-write命令",
  },
  "l7-computer-numa": {
    primary:
      "CPUからlocal memoryとremote memoryへの距離でlatencyや帯域が変わるため、threadと利用pageの配置を揃える",
    alternate:
      "socketをまたぐmemory accessのcostを考慮し、CPU affinityとmemory allocationの局所性を合わせる",
  },
  "l7-computer-branch-prediction": {
    primary:
      "誤った経路で投機実行した後続命令を破棄し、正しい分岐先からpipelineを再充填するpenaltyが生じる",
    alternate:
      "prediction missではwrong-pathの処理をflushしてfetchをやり直すため、pipelineが深いほどcostが大きくなり得る",
  },
  "l7-design-idempotency-key": {
    primary:
      "再送を同じ論理操作として識別し、最初の処理結果を再利用して決済などの副作用を重複実行しないため",
    alternate:
      "timeout後のretryでも同じkeyとrequestを照合し、すでに完了または進行中の処理を二重に開始しないため",
  },
  "l7-design-sharding-strategy": {
    primary:
      "range分割は近いkeyを同じshardへ置いて範囲検索を局所化し、hash分割はkeyを散らして負荷を均しやすい",
    alternate:
      "rangeはkey空間の境界で配置を決め、hashはhash値で配置を決めるため、局所性と分散均等性の特性が異なる",
  },
  "l7-network-gossip-protocol": {
    primary:
      "各nodeが選んだ少数のpeerと情報を反復交換し、中央coordinatorなしで確率的にcluster全体へ伝播させる",
    alternate:
      "randomなpeer間のpush/pullを繰り返し、即時到達ではなくeventualな収束としてmembershipなどを共有する",
  },
  "l7-network-cdn-origin-shield": {
    primary:
      "複数edgeのcache missを上位cacheへ集約し、同じobjectについてoriginへ到達するrequestと転送量を減らす",
    alternate:
      "edgeとoriginの間に共有cache層を置き、分散したedge missを高いcache hit率とrequest集約へ変える",
  },
  "l7-security-mtls": {
    primary:
      "server認証に加えてclient証明書も検証し、通信を開始したworkloadのidentityを相互に確認できる",
    alternate:
      "TLS handshakeで双方が証明書を提示・検証し、service間通信で接続先だけでなく接続元も認証する",
  },
  "l7-security-sandbox-escape": {
    primary:
      "隔離境界の実装上の欠陥を悪用し、sandbox内のcodeからhostや他tenantなど境界外のresourceへ到達する攻撃",
    alternate:
      "container・browser・VMなどの制限を破り、本来許可されないhost syscallやmemory、credentialへアクセスする脅威",
  },
};

const sharperDistractors: Record<string, DistractorTexts> = {
  "l1-computer-binary": [
    "0と1にすると論理演算は単純になるが、主な理由は情報量が必ず最小になること",
    "2進数は文字列や画像を直接表せるので、CPUが解釈する約束を別に持たなくてよいから",
    "10進数より表現できる値の種類が多く、同じ桁数なら必ず多くの情報を持てるから",
    "ネットワーク通信がビット単位なので、メモリやCPUも同じ粒度でしか動けないから",
    "0と1で表せば、ノイズの影響を完全に消せてエラー訂正が不要になるから",
  ],
  "l1-computer-memory-storage": [
    "メモリはCPUに近い高速な保存場所で、ストレージと同じく通常は電源断後も残る",
    "ストレージは実行中の一時データ、メモリはファイルやDBを長期保存する場所",
    "メモリはOSだけが使う領域で、アプリケーションの変数や配列はストレージに置かれる",
    "メモリとストレージはどちらも永続化されるが、違いは暗号化できるかどうか",
    "WebアプリではDBがあるため、メモリとストレージの違いを意識する場面はほぼない",
  ],
  "l1-computer-process": [
    "プロセスはCPUが実行する最小単位で、同じプロセス内に複数のメモリ空間を持つ",
    "プロセスはスレッドをまとめる概念だが、OSから資源を割り当てられる単位ではない",
    "プロセスはプログラムのソースコードそのもので、起動前からメモリ空間を持つ",
    "プロセスは1つのHTTPリクエストごとに必ず作られ、レスポンス後に必ず破棄される",
    "プロセスはコンテナと同じ意味で、OS上ではコンテナ単位でしか実行を管理しない",
  ],
  "l1-design-abstraction": [
    "抽象化は詳細を隠すことなので、内部実装を一切変更できないよう固定すること",
    "抽象化は呼び出し側に全ての選択肢を渡し、どんな使い方も許可すること",
    "抽象化は重複を減らすためなら、関係の薄い処理も同じ関数に集めること",
    "抽象化は将来使うかもしれない機能を先に一般化して、分岐を増やしておくこと",
    "抽象化は外部APIのレスポンスをそのまま全層へ伝搬させ、変換をなくすこと",
  ],
  "l1-design-interface": [
    "インターフェースでは内部のDBスキーマや利用ライブラリまで公開し、利用側が細かく制御できるようにする",
    "インターフェースは使う側の自由度を最大化するため、入力型やエラー条件をなるべく曖昧にする",
    "インターフェースは実装を隠すものなので、失敗時に何が返るかは実装側だけが知っていればよい",
    "インターフェースは初回リリース時に決まるものなので、後方互換性より実装速度を優先してよい",
    "インターフェースはUI部品だけに関係し、APIや関数の入出力にはあまり関係しない",
  ],
  "l1-network-dns": [
    "DNSはブラウザがHTTPレスポンスをキャッシュする仕組みで、IPアドレス解決とは別である",
    "DNSはドメイン名とサーバ証明書を対応づけ、証明書が正しければIPアドレスは不要になる",
    "DNSはURLのパスやクエリまで見て、どのアプリケーションルートへ送るかを決める",
    "DNSはCDNがある場合だけ使われ、通常のサーバへ直接接続する場合は使われない",
    "DNSは名前をIPアドレスへ変換するが、結果は毎回ブラウザが権威DNSへ直接問い合わせる",
  ],
  "l1-network-http-request-response": [
    "HTTPはクライアントとサーバが常時双方向に状態を同期し続ける通信モデルである",
    "HTTPではサーバが最初にレスポンスを送り、クライアントが後から必要なリクエストを補足する",
    "HTTPはリクエスト/レスポンスを扱うが、ステータスコードやヘッダーはTCP層が決める",
    "HTTPはブラウザ専用の通信方式で、サーバ間APIやモバイルアプリでは通常使わない",
    "HTTPは1つの接続につき必ず1リクエストだけを送り、複数リソース取得には使えない",
  ],
  "l1-network-status-codes": [
    "404は認証が必要なリソースにログインしていないことを示すため、通常はログイン画面へ誘導する",
    "404はサーバ内部エラーを隠すために返す汎用コードで、リソースの存在有無とは関係しない",
    "404はHTTPメソッドが許可されていないことを示し、同じURLでもGETなら成功する可能性が高い",
    "404はURLのドメイン名がDNSで解決できない状態を、HTTPレスポンスとして表したもの",
    "404はキャッシュが古いときだけ返るコードで、キャッシュ削除により必ず解決する",
  ],
  "l1-security-authn-authz": [
    "認証は権限を割り当てること、認可はユーザーが本人かどうかを確認すること",
    "認証に成功したユーザーは基本的に全操作を許可してよく、細かい制御はUI側で行う",
    "認可はログイン前だけに必要で、ログイン後の操作では認証だけ確認すれば十分",
    "認証と認可はどちらもパスワード検証のことで、ロールや所有者チェックは別の概念",
    "認可はフロントエンドの表示制御を指し、サーバ側のアクセス制御とは切り離して考える",
  ],
  "l1-security-hash-encryption": [
    "ハッシュ化は鍵があれば復号でき、暗号化は通常元に戻せない一方向変換である",
    "暗号化もハッシュ化も元に戻せるが、ハッシュ化の方が復号に時間がかかる",
    "ハッシュ化は主に通信経路を秘匿するために使い、暗号化は同一性確認にだけ使う",
    "ハッシュ化は同じ入力でも毎回ランダムな出力になるので、照合には向かない",
    "パスワード保存では後で通知できるよう、暗号化して復号可能にするのが基本である",
  ],
  "l2-computer-latency": [
    "I/O待ちはCPU使用率を高めるため、CPU最適化を先に行うほど改善しやすいから",
    "DBや外部APIはネットワーク越しでもOSがメモリと同じ速度で扱うため、差は主にコード量で決まるから",
    "Webアプリの遅さはほぼJavaScriptの構文選択で決まり、I/Oは非同期なら無視できるから",
    "I/O待ちは並列化すれば必ずゼロにできるため、設計上のボトルネックにはならないから",
    "CPU処理は常に外部APIより遅いので、I/Oより計算量だけを測れば十分だから",
  ],
  "l2-computer-stack-heap": [
    "スタックは長期保存したいオブジェクトを置く領域で、ヒープは関数呼び出しごとに自動で積まれる領域",
    "スタックとヒープはいずれもDB上の領域で、アプリの実行メモリとは別に管理される",
    "スタックはGCが回収する領域、ヒープは関数終了時に必ず即時解放される領域",
    "JavaScriptでは全てヒープに置かれるため、再帰やコールスタックの問題は起きない",
    "スタックはOSだけが使い、アプリケーションの関数呼び出しとは直接関係しない",
  ],
  "l2-computer-process-thread": [
    "プロセスとスレッドはどちらも同じメモリ空間を共有するが、スレッドの方がOS上で強く分離される",
    "プロセスはスレッドより軽量なので大量作成に向き、スレッドは分離が強いので安全性に向く",
    "スレッドは独立したメモリ空間を持ち、プロセスは同じメモリを共有する実行単位である",
    "Webサーバではイベントループがあるため、プロセスやスレッドの違いはスケール設計に影響しない",
    "プロセスとスレッドの違いはCPUコア数だけで決まり、メモリ共有や分離とは関係しない",
  ],
  "l2-design-coupling-cohesion": [
    "疎結合は全ての依存を消すことで、高凝集は全機能を1つのモジュールに集めること",
    "疎結合を高めるには、各層が互いの内部構造を詳しく知っている方が変更に強い",
    "高凝集は似た名前の処理を集めることで、同じ理由で変更されるかは重視しない",
    "疎結合・高凝集は小規模アプリでは不要で、テストや保守性にはほぼ影響しない",
    "疎結合は抽象化を増やすほど必ず良くなり、理解コストや追跡コストは考えなくてよい",
  ],
  "l2-design-idempotency": [
    "冪等性はリクエストの実行結果が必ず成功することなので、失敗時の再試行とは関係しない",
    "冪等なAPIは何度呼んでもサーバログや更新時刻を含めて一切変化してはいけない",
    "POSTは仕様上必ず冪等なので、二重決済を避けるための追加設計は不要である",
    "冪等性は読み取りAPIだけの性質で、作成や更新のAPIでは考えても意味がない",
    "冪等キーを使えば、処理結果の保存や重複判定をサーバ側で行わなくても安全になる",
  ],
  "l2-network-tcp-ip": [
    "HTTPはTCP/IPより下位でパケット配送を担当し、TCPがリクエストやステータスコードを解釈する",
    "HTTPとTCP/IPは同じアプリケーション層のプロトコルで、どちらを使うかはAPI設計だけで決まる",
    "TLSはHTTPのヘッダー圧縮方式なので、暗号化とは別にTCPの下で動く",
    "IPは接続の信頼性を保証し、TCPは宛先アドレスを名前解決する役割を持つ",
    "HTTP/2やHTTP/3でも必ずTCPの上で動くため、QUICのような別の輸送層は考えなくてよい",
  ],
  "l2-network-dns-ttl": [
    "TTLが長いと権威DNSの値そのものが変更できなくなり、設定を戻すまで問い合わせが失敗する",
    "TTLが長いほどブラウザはHTTPレスポンスを長く保存するため、HTML更新が反映されにくくなる",
    "TTLはTLS証明書の有効期限を表すので、長いほど証明書ローテーションが難しくなる",
    "TTLが長いとDNS問い合わせが増え、権威DNSへ負荷が集中しやすくなる",
    "TTLはCDNキャッシュだけに関係し、OSやリゾルバの名前解決結果には影響しない",
  ],
  "l2-network-http-methods": [
    "GETは安全だがサーバ状態を変えてもよく、POSTはキャッシュできないので読み取り専用に使う",
    "GETとPOSTの違いはURLにクエリを含められるかどうかだけで、意味上の使い分けはない",
    "POSTは通信内容がURLに出ないため、GETより常にセキュアでCSRF対策も不要になる",
    "GETはボディを送れないため、検索条件が複雑な場合は必ずPOSTで状態変更APIにする",
    "HTTPメソッドはサーバ実装が自由に決めるラベルなので、リトライやキャッシュの判断には使わない",
  ],
  "l2-security-tls": [
    "HTTPSは通信を暗号化するが、接続先の正当性確認や改ざん検知はHTTPヘッダーが担う",
    "HTTPSにするとアプリ層の入力検証も不要になり、XSSやSQLインジェクションも防げる",
    "TLSはサーバ証明書だけでなくユーザー認可も行うので、ログインセッションは不要になる",
    "HTTPSはブラウザとCDNの間だけを守る仕組みで、オリジンまでの通信には使えない",
    "HTTPSはレスポンス本文だけを暗号化し、URLのホスト名や接続先の情報は全て隠せる",
  ],
  "l2-security-password-storage": [
    "パスワードは後でユーザーへ再通知できるよう、アプリの共通鍵で暗号化して保存する",
    "SHA-256のような高速ハッシュに全ユーザー共通のsaltを足せば、パスワード保存には十分である",
    "フロントエンドでハッシュ化してから送れば、サーバ側ではその値を平文パスワードとして保存してよい",
    "Base64やURLエンコードで可読性を下げれば、漏洩時にも元のパスワードは実質守られる",
    "パスワードハッシュを使う場合、ログイン試行のレート制限やリセット導線は不要になる",
  ],
  "l3-computer-concurrency-parallelism": [
    "並行は複数CPUコアで同時に実行することで、並列は1つのコアで切り替えながら扱うこと",
    "イベントループはI/O待ちを扱えるので、CPU負荷の高い処理も自動的に並列実行される",
    "並行性を入れると処理順序は常に保証されるため、競合やキャンセルを考える必要はない",
    "並列処理は複数タスクを設計上扱うことで、実際に同時実行されるかは関係しない",
    "並行と並列は性能の言い換えで、設計や正しさにはほとんど影響しない",
  ],
  "l3-computer-sync-async": [
    "非同期処理は処理そのものを別CPUで実行する仕組みなので、CPU boundな処理ほど効果が高い",
    "awaitを付ければ全てのI/Oが同時に走るため、Promise.allのような制御は不要になる",
    "非同期処理では例外が呼び出し元に同期的に伝播するため、try/catchだけで全て扱える",
    "非同期にすると処理順序の依存がなくなるため、タイムアウトやキャンセルは基本的に不要である",
    "非同期I/Oはサーバの応答性を上げるが、外部API自体のレイテンシは必ず短縮される",
  ],
  "l3-design-cache-invalidation": [
    "キャッシュは一度作れば元データより常に正しいので、更新時の削除や再検証は不要である",
    "TTLを短くすれば古いデータ問題は完全に消えるため、キー設計や削除戦略は考えなくてよい",
    "キャッシュは読み取りを速くするだけなので、認可やユーザー別レスポンスとは切り離してよい",
    "更新時に全キャッシュを毎回削除すれば、性能や可用性への影響を考えずに常に最適になる",
    "ブラウザキャッシュとCDNキャッシュは同じ層なので、Cache-Controlだけで全て同じ挙動になる",
  ],
  "l3-design-api-versioning": [
    "レスポンスの型変更はサーバ側だけで完結するため、クライアントが古くても基本的に壊れない",
    "新しい必須項目をリクエストに追加しても、未指定時にサーバが推測すれば破壊的変更ではない",
    "URLにv2を付ければ互換性問題は解決するので、移行期間や非推奨告知は不要である",
    "フィールド名を変えても意味が同じなら、既存クライアントは自動的に追従できる",
    "APIの後方互換性は外部公開APIだけの問題で、社内サービス間では意識しなくてよい",
  ],
  "l3-design-normalization": [
    "正規化はJOINを減らして読み取りを速くするための設計で、重複や更新不整合は主目的ではない",
    "正規化を進めるほどアプリコードは常に単純になり、クエリやトランザクションは複雑にならない",
    "正規化は全ての重複を禁止するので、集計テーブルやキャッシュテーブルは設計として誤りである",
    "正規化はNoSQLやドキュメントDBでは不要で、データ整合性を考える場面もほぼない",
    "正規化では外部キー制約だけを追加すればよく、テーブル分割や関数従属性は考えなくてよい",
  ],
  "l3-network-http-cache": [
    "no-storeは保存してもよいが、再利用前に必ずオリジンへ検証するという意味である",
    "no-storeはブラウザキャッシュだけに効き、CDNや中間キャッシュには影響しない",
    "no-storeを付けるとCookieも保存されなくなるため、ログイン状態を残したくない画面で使う",
    "no-storeはレスポンス本文だけを保存禁止にし、ヘッダーやURLはキャッシュしてよいという意味である",
    "no-storeはmax-age=0と同じ意味なので、ETagがあれば機密情報にも安全に使える",
  ],
  "l3-network-cors": [
    "CORSはサーバ間通信にも適用されるため、APIサーバが別APIを呼ぶときもブラウザと同じ制限を受ける",
    "CORSは別オリジンへのリクエスト送信自体を必ず止める仕組みで、サーバには到達しない",
    "Access-Control-Allow-Originを広げれば認証や認可も同時に許可されるため、権限チェックは不要になる",
    "CORSエラーはDNSやTLSの失敗をブラウザが同じ見た目で表示しているだけで、HTTPヘッダーとは関係しない",
    "preflightが成功すれば、その後のリクエストはCSRF対策なしでも安全に状態変更できる",
  ],
  "l3-security-cookie-session": [
    "セッションCookieにはログインユーザーの権限や個人情報を平文で入れ、サーバ側の状態を減らすのが基本",
    "Cookieはブラウザに保存されるだけなので、リクエスト時に自動送信されることは通常ない",
    "HttpOnlyを付けるとサーバ側でもCookieを読めなくなるため、セッション認証には使えない",
    "CookieセッションならCSRFの影響を受けないので、SameSiteやトークンは主にJWT用の対策である",
    "セッションIDは推測されにくければ署名や失効管理は不要で、ログアウト時もブラウザ削除だけで十分である",
  ],
  "l3-security-xss": [
    "XSSは攻撃者がサーバへSQLを注入して、DB内のスクリプトを直接実行する脆弱性である",
    "入力時にHTMLタグを全て禁止すれば、出力先の文脈に関係なくXSSは完全に防げる",
    "HttpOnly Cookieを付ければXSS自体が発生しなくなるため、出力エスケープは不要になる",
    "Reactなどのフレームワークを使えば、dangerouslySetInnerHTMLを含めてXSSは自動的に防がれる",
    "XSSはログイン済みユーザーには影響しにくく、主に公開ページの見た目だけを壊す問題である",
  ],
  "l3-security-csrf": [
    "CSRFは攻撃者が被害者のパスワードを盗む攻撃なので、パスワードハッシュを強くすれば防げる",
    "CSRFはCORSで許可していない別オリジンからはリクエストが送れないため、CORS設定だけで十分である",
    "SameSite=NoneにするとCookieが送られなくなるため、CSRF対策として最も安全である",
    "状態変更をPOSTにすればブラウザが勝手に送ることはないので、CSRFトークンは不要である",
    "CSRFはAuthorizationヘッダー方式でもCookie方式でも全く同じ条件で成立する",
  ],
  "l4-computer-db-index": [
    "検索が遅い場合は、WHEREに出てくる全ての列へ単独インデックスを貼るのが最初の判断である",
    "インデックスは読み取り専用の補助構造なので、INSERTやUPDATEの性能にはほとんど影響しない",
    "複合インデックスでは列の順序より列数が重要で、実行計画を見なくても効果は予測できる",
    "カーディナリティが低い列ほど絞り込みに強いので、boolean列から優先的に貼るとよい",
    "ORMを使っていればクエリは最適化されるため、DB側の実行計画を見る必要はあまりない",
  ],
  "l4-computer-n-plus-one": [
    "N+1はJOINを使ったときだけ起きる問題で、ORMの関連取得では通常発生しない",
    "N+1はクエリ数ではなくレスポンスJSONのネストが深くなる問題なので、整形処理で解決できる",
    "Nが小さい開発環境で問題なければ、本番でもDB接続プールが吸収するため大きな問題にはなりにくい",
    "N+1は全てJOINで解消するのが正しく、batchingやpreloadを使うとデータ不整合が起きる",
    "N+1はキャッシュを入れれば根本原因を見なくても常に解決できる性能問題である",
  ],
  "l4-design-retry-backoff": [
    "外部APIが失敗したら、ユーザー体験を守るため成功するまで即時リトライし続けるのが基本である",
    "タイムアウトは成功か失敗か不明なので、冪等性を考えずに同じリクエストを再送してよい",
    "4xxはクライアント側の一時的な問題なので、5xxより優先的にリトライ対象にする",
    "指数バックオフは自サービスの負荷を下げるためで、相手サービスへの影響は考えなくてよい",
    "リトライ回数を増やせば可用性は単調に上がるため、最大回数やジッターは不要である",
  ],
  "l4-design-graceful-degradation": [
    "一部機能が落ちた場合でも整合性を保つため、全機能を同時に停止して同じエラー画面を返す",
    "劣化運転は障害を隠すためのものなので、ログやアラートは通常より抑えるべきである",
    "フォールバックを入れると本来の障害に気づけなくなるため、ユーザー向け機能では避けるべきである",
    "重要機能と補助機能を分けるより、全依存サービスを同じタイムアウト値で扱う方が公平である",
    "graceful degradationはフロントエンドだけの表示設計で、バックエンドの依存関係には関係しない",
  ],
  "l4-design-contract-compatibility": [
    "レスポンスへ必須フィールドを追加するだけなら、古いクライアントは無視するので移行設計は不要である",
    "サーバとクライアントを同時にデプロイすれば、モバイルや外部連携でも互換性問題は避けられる",
    "APIの契約は型定義が最新なら十分で、実際の古いクライアントの挙動を考慮しなくてよい",
    "必須項目を追加する場合は、ステータスコードを200に固定すれば既存クライアントは壊れにくい",
    "互換性はURLバージョンだけで表現すればよく、デフォルト値や段階移行は設計しなくてよい",
  ],
  "l4-network-reverse-proxy": [
    "X-Forwarded-Forは標準的なヘッダーなので、インターネットから来た値でも改ざんされない前提で使える",
    "複数プロキシを経由した場合、最も右のIPが常に元クライアントなので、それだけを採用すればよい",
    "TLS終端がプロキシにある場合、X-Forwarded-Forも暗号化されるためアプリ側で検証は不要である",
    "レート制限ではX-Forwarded-Forを使うより、常にTCP接続元IPだけを使えばCDN配下でも正確になる",
    "リバースプロキシがある構成では、アプリはクライアントIPを知る必要がないためログにも残さない",
  ],
  "l4-network-cdn-cache": [
    "認証済みレスポンスでもHTTPSなら他ユーザーに見えないので、CDN共有キャッシュに置いてよい",
    "Cookieを含むリクエストはCDNが自動的に全てキャッシュ対象外にするため、設定確認は不要である",
    "Varyヘッダーを増やすほどキャッシュ漏洩は防げるので、全リクエストヘッダーをVaryに入れるのがよい",
    "短いTTLなら個人別レスポンスを共有キャッシュしても、漏洩時間が短いため実務上問題になりにくい",
    "キャッシュキーにURLだけを使う設計はシンプルなので、認可付きAPIでもまず採用するべきである",
  ],
  "l4-security-rate-limit": [
    "ログインAPIのレート制限はIP単位だけで十分で、アカウント単位や失敗回数は見る必要がない",
    "レート制限を強くすればパスワードハッシュやMFAの重要性は下がるため、認証設計を簡略化できる",
    "攻撃を止めるにはログイン失敗時だけ制限し、成功時やパスワードリセットは対象外にするのがよい",
    "レート制限は全ユーザーに同じ閾値を固定すればよく、NATや正規ユーザー巻き込みは考えなくてよい",
    "レート制限で拒否すると攻撃者にヒントを与えるので、監査ログやアラートは残さない方がよい",
  ],
  "l4-security-least-privilege": [
    "開発効率を考えると、本番操作が必要な可能性のある人には事前に広い権限を付けておく",
    "最小権限は人間ユーザーだけに適用すればよく、CIやサービスアカウントは管理者権限でよい",
    "読み取り権限なら漏洩しても変更できないため、個人情報や秘密情報へのアクセスは広くしてよい",
    "一時的に強い権限を付けた場合、監査ログがあれば期限や剥奪は必須ではない",
    "UIで操作ボタンを隠せば実質的に権限を制限できるので、サーバ側チェックは補助的でよい",
  ],
  "l4-security-secrets": [
    "APIキーは環境変数に入れれば、クライアント向けJavaScriptへ埋め込んでも秘密として扱える",
    "一度Gitへ入れたシークレットも、削除コミットを積めば履歴から参照できなくなるので安全である",
    "Base64化したキーは人間に読みにくいので、設定ファイルに置いてもシークレット管理として十分である",
    "本番と開発で同じAPIキーを使うと管理が簡単になり、漏洩時のローテーションもしやすくなる",
    "ログに一部でもキーを出しておけば障害調査が楽になるため、マスキングは運用後に考えればよい",
  ],
  "l5-computer-url-to-render": [
    "URL入力後はHTTPリクエストを送り、レスポンス後に必要ならDNSやTLSの検証を行う流れで説明する",
    "CDNがある場合はブラウザがDNSやTLSを意識しないため、HTML解析とJS実行だけ説明すれば十分である",
    "ブラウザ表示までの流れはサーバ側レンダリングだけで決まり、CSS/JS/画像の追加取得は重要ではない",
    "TLSはHTTPレスポンスを受け取った後に改ざんを検知する仕組みなので、接続前の手順には含めない",
    "HTTP/2以降ではTCPやQUICの接続確立が不要になるため、ネットワーク層の説明は省略できる",
  ],
  "l5-computer-race-condition": [
    "同時購入はフロントエンドのボタン二重クリック対策を入れれば解決でき、DB側の制御は不要である",
    "在庫数を読み取ってから減算する処理を高速化すれば、同時実行でも競合は実質起きなくなる",
    "APIをPOSTではなくPUTに変更すれば冪等になるため、在庫の二重減算も防げる",
    "アプリサーバを1台にすればリクエストは必ず順番に処理されるため、トランザクションは不要である",
    "最終的に在庫が負にならなければよいので、購入成功レスポンスが二重に返ることは許容できる",
  ],
  "l5-design-availability-consistency": [
    "整合性を高めるには全ての読み取りをキャッシュから返すのが基本で、DBへの確認は可用性を下げる",
    "可用性を高めたい場合でも、全データを常に強整合にすればユーザー体験と性能は両立できる",
    "分散システムではネットワーク分断をアプリが検知できるので、分断中も常に最新値を返せる",
    "最終的整合性はデータ不整合を放置する設計なので、ユーザー向けWebアプリでは採用しない",
    "可用性と整合性の判断は技術選定だけで決まり、ドメイン上のリスクやUXとは切り離してよい",
  ],
  "l5-design-monolith-microservices": [
    "マイクロサービスはサービスごとにDBを共有すれば一貫性が保てるため、分散設計の難しさが下がる",
    "チームが増える前でも、将来を見越して最初から細かく分ければ長期的な変更容易性が必ず上がる",
    "モノリスはデプロイ単位が1つなので、機能境界を整理しても保守性を上げる余地はほぼない",
    "マイクロサービス化するとネットワーク越しの呼び出しになるため、モジュール内呼び出しより失敗しにくい",
    "独立デプロイできるなら、データ所有や監視、障害対応の複雑さは大きな論点ではない",
  ],
  "l5-design-observability": [
    "ログに全ての情報を出せば、メトリクスやトレースは重複するため基本的に不要である",
    "メトリクスは個別リクエストの原因調査に最も向いており、ログは全体傾向を見るのに向いている",
    "トレースは単一サーバ内では役立つが、サービス間の遅延や依存関係を見る用途には向かない",
    "相関IDはログ量を増やすだけなので、障害調査ではユーザーIDやIPだけで追跡すれば十分である",
    "観測性は障害後にログを増やせばよいので、設計時にどの情報が必要か考える優先度は低い",
  ],
  "l5-network-dns-tls-failure": [
    "安全ではない警告はアプリの認証エラーなので、まずログインセッションとCookie属性を見る",
    "DNSが正しければ証明書警告は起きないため、証明書のSANや期限は後回しでよい",
    "証明書が有効なら混在コンテンツやリダイレクト設定で警告が出ることはない",
    "CDNを使っていれば証明書は自動的に全ドメインへ発行されるため、独自ドメイン設定は不要である",
    "ブラウザの警告はキャッシュが原因のことが多いので、まずユーザーにキャッシュ削除を案内する",
  ],
  "l5-security-secure-cookie": [
    "HttpOnlyはCookieをHTTPSでのみ送る属性で、SecureはJavaScriptからの読み取りを防ぐ属性である",
    "SameSite=Strictを付ければ全てのCSRFが防げるため、重要操作のトークン検証は不要になる",
    "Secure Cookieはサーバ側でしか読めないため、セッションIDを盗まれるリスクを完全に消せる",
    "HttpOnlyを付けるとXSSが発生しなくなるので、出力エスケープやCSPの優先度は下がる",
    "Cookie属性はブラウザ保存時の制御なので、サブドメインやプロキシ構成とは関係しない",
  ],
  "l5-security-threat-modeling": [
    "脅威モデリングでは実装後に発生した攻撃だけを洗い出し、事前に仮説を置くことは避ける",
    "新規登録ではパスワード保存だけを見ればよく、botやメール所有確認は運用で対応すればよい",
    "HTTPSを使えば登録フォームの盗聴は防げるため、なりすましや乱用は主要な脅威ではない",
    "脅威は全て同じ重要度で扱い、対策コストより網羅性を優先して全て同時に潰す",
    "ユーザー体験を損ねないため、登録時のレート制限やメール確認はセキュリティ要件に含めない",
  ],
  "l5-network-performance-bottleneck": [
    "Webページが遅い場合はまずJSバンドルを削るのが定石で、TTFBやDNSは後から見る",
    "LCPが悪いときはサーバ処理が原因とは限らないが、ネットワークウォーターフォールは見なくてよい",
    "平均レスポンス時間が良ければ、p95や低速回線の体験は個別環境の問題として扱える",
    "CDNを入れればサーバ処理、画像、JS実行、レンダリングの問題はまとめて解消できる",
    "Core Web Vitalsはフロントエンドだけの指標なので、APIやDBの遅さとは切り離して調査する",
  ],
  "l5-security-incident-explanation": [
    "インシデント後はまず再発防止策を発表し、影響範囲は調査完了まで触れない方が混乱が少ない",
    "原因が分かるまでは暫定情報を出さず、復旧後に技術詳細だけをまとめれば十分である",
    "封じ込めより根本原因分析を先に行うことで、同じ攻撃を完全に理解してから対応できる",
    "ユーザー影響が小さい場合は、監査ログやタイムラインを残さず通常のバグ修正として扱う",
    "報告では技術的な正確性より安心感を優先し、推測も含めて断定的に説明する",
  ],
  "l1-computer-cpu-ram": [
    "CPUは命令と実行中dataを長期保存し、RAMは保存された命令を順番に実行する装置",
    "CPUとRAMはどちらも計算を担当し、CPUは整数演算、RAMは文字列処理を専門にする",
    "CPUは電源断後も内容が残る主記憶で、RAMは再起動時だけ使う一時的な処理装置",
    "CPUはOSだけを実行し、application codeはRAM内の回路が直接実行するという役割分担",
    "CPUはnetwork I/Oを担当し、RAMはdisk I/Oを担当することで処理を並列化する装置",
  ],
  "l1-computer-os-kernel": [
    "起動したapplicationの画面と業務logicを管理し、hardware資源は各processへ直接操作させる部分",
    "commandを解釈してprogramを起動するshellのことで、memory保護やdevice制御は担当しない部分",
    "machine起動時にOSをmemoryへ読み込むbootloaderで、起動後は実行に関与しない部分",
    "programming languageのcodeをmachine語へ変換し、processごとの実行順だけを決める部分",
    "virtual machine上でguest OSを分離するhypervisorと同じで、通常のprocess管理は行わない部分",
  ],
  "l1-network-tcp-udp": [
    "TCPは通信内容を暗号化し、UDPは平文で送るというsecurity機能だけの違い",
    "TCPは一件ごとのmessage境界を保ち、UDPは複数messageを一つの連続streamとして渡す",
    "TCPはpacket lossを許容して再送せず、UDPは欠落packetをtransport層で自動再送する",
    "TCPはserver間通信、UDPはbrowser通信に使うという利用applicationによる分類",
    "TCPはIPv4専用、UDPはIPv6専用で、IP versionに合わせて選ぶtransport protocol",
  ],
  "l1-security-cia": [
    "Confidentiality、Identity、Authenticationで、秘密保持・本人確認・認証を表す",
    "Consistency、Isolation、Availabilityで、transactionの一貫性・分離性・可用性を表す",
    "Confidentiality、Integrity、Authenticationで、機密性・完全性・認証を表す",
    "Certificate、Identity、Authorizationで、証明書・主体確認・権限判定を表す",
    "Confidentiality、Inspection、Auditで、暗号化・検査・監査記録を表す",
  ],
  "l1-design-abstraction-leak": [
    "内部実装をinterfaceの後ろへ隠した結果、利用側が実装classの名前を知らずに使える状態",
    "利用側へ入力条件とerrorを明示し、内部の制約を公開されたcontractとして扱っている状態",
    "異なる実装を同じinterfaceで差し替えられ、利用側のcodeを変更せずに動かせる状態",
    "内部処理を小さなprivate関数へ分け、外部へ公開するmethod数を減らしている状態",
    "性能上重要な制約をdocumentへ記載し、利用側がcontractとして明示的に判断できる状態",
  ],
  "l1-design-dry": [
    "似た形のcodeは意味が異なっていても一つの汎用関数へまとめ、分岐で差を吸収すること",
    "同じ処理を複数箇所へcopyし、それぞれを独立して変更できるように保つこと",
    "重複を避けるため、まだ一度しか現れていないlogicも将来を予測して共通化すること",
    "codeの行数を減らすことを優先し、異なる業務知識を短い式へまとめて表現すること",
    "同じ値を使う箇所では定数名を付けず、literalを直接書いて参照関係をなくすこと",
  ],
  "l1-design-yagni": [
    "将来必要になりそうな機能を先に実装し、要件確定後は設定で無効化しておく考え方",
    "今ある要件でも実装costが高い機能は作らず、必要性にかかわらずscopeから外す考え方",
    "設計やtestを行わず最短でcodeを書き、変更が必要になった時だけ品質を考える考え方",
    "一度追加した機能は将来また使う可能性があるため、利用されなくても削除しない考え方",
    "userが明示した要望だけを扱い、securityや運用など暗黙の要件は考慮しない考え方",
  ],
  "l1-network-http-header": [
    "HTMLやJSONなどresponseの本体dataを格納し、bodyの代わりに大きな内容を送る仕組み",
    "TCP connectionの再送回数やpacket順序を指定し、transport層の動作を直接制御する仕組み",
    "URLのhost名をIP addressへ変換し、接続先networkを決めるための名前解決情報",
    "server内部の変数とDB recordをclientへ公開し、処理状態を同期するための領域",
    "browserに表示する文字のlayoutやcolorを指定し、CSSより先に描画へ適用する情報",
  ],
  "l1-security-sql-injection": [
    "入力値をparameterとしてSQL engineへ渡した結果、値の一部がquery構文として解釈される攻撃",
    "大量の正規SQL queryを短時間に送り、DB connectionを使い切って応答不能にする攻撃",
    "推測したpasswordでDB管理画面へloginし、正規の権限でrecordを読み取る攻撃",
    "database fileのpathへ../を含め、許可directory外のfileを直接読み出す攻撃",
    "responseへscriptを埋め込み、利用者のbrowser上でSQL clientを起動させる攻撃",
  ],
  "l1-security-https-certificate": [
    "接続したuserの本人確認と操作権限を証明し、applicationの認可判定を置き換える",
    "serverが返すHTMLやJSONの内容が安全で脆弱性を含まないことをCAが保証する",
    "通信に使う共通鍵そのものを証明書へ保存し、すべてのclientへ同じ秘密鍵を配布する",
    "domain名をIP addressへ変換し、正しいserverへpacketをroutingするDNSの役割を担う",
    "通信dataを圧縮して第三者から読みにくくし、圧縮解除に公開鍵を利用する",
  ],
  "l1-computer-compiler-interpreter": [
    "compilerは実行時に一行ずつsourceを読み、interpreterは実行前にprogram全体をmachine語へ変換する",
    "compilerとinterpreterはどちらも必ず実行fileを生成し、違いはsource codeの拡張子だけにある",
    "compilerは型検査だけを行い、命令の実行はinterpreterが別processとしてすべて担当する",
    "使用するlanguageがcompiledかinterpretedかで固定され、同じlanguageに複数の実行方式は存在しない",
    "compilerはsyntax errorを実行後に検出し、interpreterはprogram全体のerrorを起動前に検出する",
  ],
  "l1-computer-bit-byte": [
    "bitは0から7までの値を表す単位で、8bitを一つのbinary digitとして扱ったものがbyte",
    "bitはCPU内部、byteはstorage内部だけで使う単位で、同じdata量を相互変換できない",
    "bitを10個まとめると1byteになり、1KBを1000byteとして扱う10進単位の関係",
    "bitは一文字を表す最小単位、byteは一つの数値を表す最小単位というdata種類の違い",
    "bitとbyteはどちらも8個の0/1を表し、通信速度ではbit、file容量ではbyteと呼び分ける",
  ],
  "l1-computer-big-o": [
    "特定machineで一回実行した秒数を入力件数で割り、hardware差を含めて比較する指標",
    "入力が平均的な場合の処理回数だけを示し、最悪caseやmemory使用量には適用しない指標",
    "source codeの行数とloop数を合計し、programの複雑さを一つの整数で表す指標",
    "入力sizeに関係なく定数項まで正確に残し、実際の処理時間を計算するための式",
    "algorithmが返す答えの精度を表し、O(1)が最も正確でO(n²)ほど誤差が大きいという尺度",
  ],
  "l1-computer-array-linked-list": [
    "arrayは各要素が次要素へのpointerを持ち、linked listは連続memoryを添字で参照する",
    "arrayは途中へのinsertが常にO(1)、linked listは先頭位置を知っていても全要素の移動が必要になる",
    "arrayは要素数を変更できないdata型だけを指し、dynamic arrayはlinked listの別名である",
    "linked listは任意位置へ添字でO(1) accessでき、arrayは先頭から順に探索する必要がある",
    "arrayは同じ型、linked listは異なる型だけを格納できるという要素型の制約による違い",
  ],
  "l1-computer-filesystem": [
    "開いたfileの内容をすべてRAMへ保持し、process終了時にだけstorageへ書き戻すmemory管理機能",
    "file拡張子から起動applicationを選び、内容を解釈して画面へ表示するlauncher機能",
    "複数machineのfileをcloudへ同期し、どの端末でも同じdirectoryを見せるnetwork service",
    "disk blockの故障を検出してhardwareを交換し、backupなしでdataを復元する装置管理機能",
    "file本文を全文index化して検索し、directory階層を使わずqueryだけでdataを管理するdatabase",
  ],
  "l1-design-encapsulation": [
    "すべてのfieldへgetterとsetterを公開し、外部から任意の値を直接設定できるようにすること",
    "dataだけをprivateにし、状態を壊し得る操作は検証せずpublic methodとして公開すること",
    "関連する全objectを一つのglobal stateへまとめ、どのmoduleからも共有変更できるようにすること",
    "classの内部実装を継承先へすべて公開し、subclassからfieldを自由に変更できるようにすること",
    "objectをJSONへ変換してnetworkへ送り、別processから同じ状態を変更できるようにすること",
  ],
  "l1-design-separation-of-concerns": [
    "一つの関心を複数fileへ均等に分散し、各fileの行数を同じ程度へ揃えること",
    "画面・業務logic・data accessを一つのclassへ集め、変更箇所を探しやすくすること",
    "team memberごとに担当fileを固定し、機能間のdependencyは共有変数で調整すること",
    "module同士を独立させるため、共通logicをそれぞれへcopyして変更を伝播させないこと",
    "異なる関心を同じinterfaceへ載せ、利用側が一つの入口から全機能を操作できるようにすること",
  ],
  "l1-design-kiss": [
    "読みやすさや変更容易性よりcodeの文字数を減らし、最短の一行で処理を書く考え方",
    "将来の全要件に対応できる汎用frameworkを先に作り、個別実装を減らす考え方",
    "外部libraryや標準機能を避け、仕組みをすべて自作してdependencyを単純にする考え方",
    "error処理や入力検証を省略し、正常caseだけの制御flowへ絞って単純にする考え方",
    "設計上の選択肢を検討せず、最初に思いついた実装を変更しないことを単純さとみなす考え方",
  ],
  "l1-design-mvc": [
    "Modelが画面表示、Viewが入力受付、Controllerがdatabase schemaだけを管理する役割分担",
    "Controllerへdata accessと全業務logicを集約し、ModelとViewを単純な値objectにする構成",
    "Modelをdatabase tableと一対一に限定し、永続化しないbusiness ruleはViewへ置く構成",
    "ViewがModelを介さずdatabaseへ直接queryし、ControllerはURL routingだけを担当する構成",
    "Model・View・Controllerをそれぞれ別serverへdeployすることを要求する分散architecture",
  ],
  "l1-design-rest-resources": [
    "操作名を/createUserや/deleteUserのようなURLへ置き、すべてPOSTで呼ぶ設計style",
    "JSONを返すHTTP APIならresource表現やmethodの意味にかかわらずRESTとする分類",
    "serverがclient sessionをmemoryへ保持し、前回requestの状態を前提に次を処理する設計",
    "GETで更新、DELETEで取得のようにmethodを自由なlabelとして使い、URLだけで意味を表す設計",
    "database tableごとに必ず一つのendpointを作り、内部schemaをresponseへそのまま公開する設計",
  ],
  "l1-network-ip-address": [
    "同じhost内で通信を受け取るapplicationを区別し、socketの配送先を決めるport番号",
    "network interfaceへ製造時に付く識別子で、routerを越えても同じ値を宛先として使うMAC address",
    "人が覚えやすいservice名を階層管理し、DNSで別の名前へ対応づけるdomain名",
    "一つのTCP connection内でbyte順序を管理し、欠落dataを検出するsequence番号",
    "user accountへproviderが割り当て、login時の本人確認に使う契約者識別番号",
  ],
  "l1-network-url-structure": [
    "schemeとhostだけがserverへ送られ、pathとqueryはbrowser内の画面切替にだけ使われる",
    "URL全体をDNSが一つのIP addressへ変換し、pathごとに異なるnetwork interfaceへ接続する",
    "query stringはresponseを受け取った後にJavaScriptだけが読み、HTTP requestには含まれない",
    "httpsはdomain所有者の種類、example.comはprotocol、/searchはport番号を表す",
    "pathはserver storage上のphysical directoryと同じでなければHTTP responseを返せない",
  ],
  "l1-network-router": [
    "MAC addressを見て同じlocal network内のportへframeを転送するswitchだけの役割",
    "domain名を権威serverへ問い合わせ、対応するIP addressをclientへ返すresolverの役割",
    "TCP connectionの欠落packetを再送し、applicationへ順序通りdataを届けるendpointの役割",
    "HTTP requestのpathを見てcontrollerを選び、HTMLやJSONを生成するweb serverの役割",
    "通信内容を暗号化して送信元を認証し、安全なtunnelを作るVPN gatewayだけの役割",
  ],
  "l1-network-bandwidth-latency": [
    "bandwidthは最初のbyteが届くまでの時間、latencyは一秒間に運べるdata量を表す",
    "bandwidthを増やせば物理距離や中継数も減るため、小さいrequestのlatencyも同じ割合で下がる",
    "latencyはdownload時、bandwidthはupload時だけ使う指標で、通信方向によって呼び分ける",
    "bandwidthはserver性能だけ、latencyはclient性能だけで決まり、network経路は影響しない",
    "どちらもbit per secondで測る回線速度の指標で、data量と待ち時間を区別しない",
  ],
  "l1-network-localhost": [
    "同じLAN内で最も応答が速いhostをDNSが自動選択し、そのaddressへ接続する特別な名前",
    "開発中のserverをinternetへ公開し、外部userからも接続できるようにする共通domain",
    "router自身を指すdefault gatewayの別名で、どのmachineから開いても同じ管理画面へ届く",
    "DNS障害時に使うpublic resolverの予備名で、8.8.8.8などへ自動変換されるhost名",
    "実行中processだけを指す名前で、別processが同じmachineのportへ接続する際には使えない",
  ],
  "l1-security-phishing": [
    "漏洩済みIDとpasswordの組を多数のserviceへ自動入力し、使い回しaccountへloginする攻撃",
    "serverの脆弱性からdatabaseへ侵入し、利用者の操作を介さずcredentialを直接取得する攻撃",
    "network経路へ割り込み、暗号化されていない通信packetからcredentialを読み取る攻撃",
    "password候補を一accountへ繰り返し試し、認証を総当たりで突破しようとする攻撃",
    "session IDを盗み、本人のpasswordを入力させず既存login状態を引き継ぐ攻撃",
  ],
  "l1-security-dos": [
    "入力へSQL構文を混ぜてdatabaseのdataを読み書きし、主に機密性や完全性を損なう攻撃",
    "通信内容を途中で書き換え、正規serverとclientの双方になりすまして完全性を損なう攻撃",
    "弱いpasswordを繰り返し試して管理accountを取得し、権限境界を破る攻撃",
    "responseへscriptを混入させ、閲覧者のbrowser上でsession情報を操作する攻撃",
    "software更新へ悪意あるcodeを混ぜ、正規配布経路から利用者へ侵入する攻撃",
  ],
  "l1-security-symmetric-asymmetric": [
    "共通鍵暗号は公開鍵と秘密鍵のpairを使い、公開鍵暗号は双方が同じ秘密鍵を共有する",
    "共通鍵暗号は一方向で復号できず、公開鍵暗号だけが元dataを取り出せる変換方式",
    "共通鍵暗号は本人確認だけ、公開鍵暗号はdata圧縮だけに使うという用途の違い",
    "共通鍵暗号は鍵をnetworkへ公開し、公開鍵暗号は公開鍵も秘密に保つという管理方法",
    "共通鍵暗号は文字列、公開鍵暗号は数値だけを処理できるというdata型による分類",
  ],
  "l1-security-brute-force": [
    "他serviceから漏れた正しいID・passwordの組だけを別serviceで試すcredential stuffing",
    "正規siteを装った入力画面を用意し、user自身にpasswordを入力させるphishing",
    "login後のsession IDを盗み、passwordを推測せずaccountとして通信するsession hijacking",
    "password reset URLのtokenを盗み、認証手順を経ずに新しいpasswordへ変更する攻撃",
    "response時間の差を繰り返し測り、比較中の秘密値を一文字ずつ推測するtiming attack",
  ],
  "l1-security-vulnerability-patch": [
    "仕様と異なる動作をするbug全般で、attackへ利用できるかにかかわらずすべて脆弱性と呼ぶ",
    "脆弱性が公開されてから修正版を適用していない状態だけを指し、未公開の弱点は含まない",
    "source codeが公開され、第三者が内部実装を読めるopen source softwareの性質を指す",
    "performanceが目標値を下回り、peak trafficを処理できないcapacity不足だけを指す",
    "userが複雑な操作を必要とする使いにくさで、security上の影響がなくても脆弱性と呼ぶ",
  ],
  "l2-computer-two-complement": [
    "最上位bitを符号だけに使い、残りのbitを正数と同じ絶対値として読む符号付き表現",
    "負数の全bitを反転するだけで表し、+0と-0の二種類を残して比較を単純にする表現",
    "負数を10進文字列として保存し、演算時だけbinaryへ変換してoverflowを防ぐ表現",
    "符号bitを持たずに全bitを大きさへ使い、負数は別の型情報で区別する表現",
    "小数点位置を指数部へ記録し、整数と浮動小数点を同じ加算回路で扱う表現",
  ],
  "l2-computer-utf8": [
    "Unicodeは文字をbyte列へ変換する一つのencodingで、UTF-8はその文字一覧のversion名",
    "Unicodeはfontの字形を定義し、UTF-8は画面上の文字幅や描画順を指定する形式",
    "UTF-8は各文字を一律8bitで保存し、Unicodeのcode pointと同じ数値をそのまま書く方式",
    "UnicodeとUTF-8は同じ規格の別名で、UTF-16とは扱える文字の種類だけが異なる",
    "Unicodeは日本語など非ASCII文字専用で、UTF-8は英数字専用に分けられた文字集合",
  ],
  "l2-network-http-acronyms": [
    "HTTPはHTML転送、TLSはtoken認証、DNSはserver発見を担い、それぞれapplication層で動く",
    "HTTPはHost Transfer Type、TLSはTransport Login Service、DNSはDomain Number Schemeの略",
    "HTTPは名前解決、TLSはdata転送、DNSは暗号化を担当し、接続時にこの順で処理する",
    "HTTPとTLSは暗号化の有無で選ぶ代替protocolで、DNSはHTTP request headerの一種である",
    "HTTPはbrowser専用、TLSはmail専用、DNSはserver間通信専用として用途が分かれている",
  ],
  "l2-security-xss-csrf-acronyms": [
    "XSSはlogin済みuserのrequestを別siteから送らせ、CSRFはresponseへscriptを混入させる問題",
    "XSSとCSRFはどちらもserver上で任意codeを実行する攻撃で、侵入口のprotocolだけが異なる",
    "XSSはSQL queryへ入力を注入し、CSRFはshell commandへ入力を注入する攻撃の分類",
    "XSSは盗まれたpasswordを総当たりし、CSRFは固定したsession IDを被害者へ使わせる攻撃",
    "XSSは通信経路の盗聴、CSRFはDNS responseの偽装によってbrowserを乗っ取る攻撃",
  ],
  "l2-design-solid-srp": [
    "一つのclassには公開methodを一つだけ置き、処理の種類にかかわらずfileを分割する原則",
    "一つのmoduleを一人のdeveloperだけが変更し、複数teamからの変更を禁止する原則",
    "関連する全処理を一つのserviceへ集め、外部依存を持たない大きな責務にまとめる原則",
    "moduleが利用するdatabaseやAPIを一つに限定し、複数のdependencyを持たせない原則",
    "変更理由が増えてもinterfaceを一つに保ち、利用側から単純に見せることを優先する原則",
  ],
  "l2-design-loose-coupling": [
    "上位層から下位層のconcrete classを直接生成し、利用するmethodだけを呼ぶようにする",
    "下位層から上位層のbusiness logicを呼び出し、互いの状態を同期して差し替えを可能にする",
    "全layerで同じglobal objectを共有し、引数やreturn valueによる依存を減らす",
    "database schemaを上位層のmodelとして直接公開し、変換codeをなくして構造を単純にする",
    "実装差を条件分岐で上位層へ列挙し、新しい実装の追加時に呼び出し側を修正する",
  ],
  "l2-design-open-closed": [
    "新しい要件には既存codeを直接修正して対応し、classやfileを増やさないよう閉じる原則",
    "一度releaseしたcodeはbugを含んでいても変更せず、追加moduleだけで修正する原則",
    "すべてのclassを継承可能に公開し、private methodを持たせないようにする原則",
    "将来の変更点をすべて先読みしてextension pointを作り、既存codeを固定する原則",
    "source codeは公開するが実行環境は閉じ、外部userからの変更を受け付けない原則",
  ],
  "l2-network-port-number": [
    "network上のhost自体を識別し、routerがpacketの宛先machineを選ぶための番号",
    "一つのTCP connection内でpacketの順序を識別し、欠落dataを再送するための連番",
    "domain名をIP addressへ対応づけ、同じserviceのserverを見つけるための番号",
    "processが開いたfileやsocketをapplication内部で区別するfile descriptorと同じ番号",
    "HTTP requestごとにserverが発行し、responseとの対応を取るための一時的なID",
  ],
  "l2-network-nat": [
    "private host名をpublic DNS recordへ変換し、外部resolverから内部端末を検索できるようにする仕組み",
    "外部から届く特定portだけを内部serverへ固定転送し、内部からの通信addressは変えない仕組み",
    "networkへ参加した端末へprivate IPを貸し出し、default gatewayやDNS設定を配布する仕組み",
    "HTTP requestをapplication proxyが中継し、client IPをheaderへ追加してserverへ渡す仕組み",
    "IPv4 packetをIPv6 packetへ変換し、内部端末にもglobal IPv6 addressを割り当てる仕組み",
  ],
  "l2-security-password-policy": [
    "8文字以上で大文字・小文字・数字・記号を必須にし、30日ごとに新しいpasswordへ変更させる",
    "覚えやすさを優先して短いpasswordを許可し、連続失敗時のaccount lockだけで補う",
    "serviceごとの使い回しを許可し、漏洩時には全serviceのpasswordを同時変更してもらう",
    "password managerからの貼り付けを禁止し、userが毎回keyboardから入力するよう求める",
    "秘密の質問を第二passwordとして必須にし、MFAよりも本人だけが知る情報を重視する",
  ],
  "l2-security-mfa-methods": [
    "passwordと秘密の質問のように、異なる内容の知識情報を二つ組み合わせる分類",
    "passwordを二回入力し、同じ知識情報を別画面で確認することで二要素とする分類",
    "email addressとuser nameを知識要素、passwordを所持要素として組み合わせる分類",
    "SMSと認証appのcodeをどちらも知識要素として扱い、passwordなしで三要素とする分類",
    "IP addressを生体要素、browser Cookieを知識要素、端末名を所持要素とする分類",
  ],
  "l2-computer-hash-table": [
    "keyを常にsort済み配列へ挿入し、binary searchのO(log n)を平均O(1)として扱うから",
    "keyの先頭文字だけを配列indexに使い、同じ文字で始まるkeyは一つの値として上書きするから",
    "全keyとvalueをCPU cacheへ固定し、memory access自体を行わずregisterだけで検索するから",
    "各entryが全entryへのpointerを持ち、どの位置からも一回の参照で目的keyへ移動できるから",
    "格納時に重複しない連番をkeyへ割り当て、元のkeyではなくその順番でだけ取得するから",
  ],
  "l2-computer-floating-point": [
    "小数演算はOSごとに異なる10進丸めを使うため、同じbinaryでも実行環境ごとに値が変わるから",
    "IEEE 754では加算のたびにrandomな誤差を加え、同じ値へ偏らないよう調整するから",
    "厳密等価演算子はinteger以外を比較するとfalseを返し、近似値かどうかを確認しないから",
    "0.3だけが文字列としてmemoryへ保存され、0.1と0.2は数値なので型が一致しないから",
    "小数部へ使えるmemoryが不足すると下位digitを削除するため、RAM容量によって結果が変わるから",
  ],
  "l2-computer-system-call": [
    "user processがdevice registerを直接操作し、完了後にkernelへ結果だけを通知する境界",
    "I/Oごとに専用processを新規起動し、そのprocessへhardware操作を委譲して終了を待つ仕組み",
    "compilerがI/O結果をbuild時に取得し、実行binaryへ定数として埋め込む最適化",
    "library関数からCPU cacheだけを更新し、kernelは一定間隔で変更をdeviceへ反映する仕組み",
    "application codeをnetwork cardへ転送し、device firmware上で同じ関数を実行する仕組み",
  ],
  "l2-computer-context-switch": [
    "現在processの全memoryをdiskへ退避し、次processのmemory全体をRAMへ読み戻す処理",
    "一つのphysical CPU coreを停止し、別coreへ電源を入れてinstruction実行を引き継ぐ処理",
    "実行中programを再compileし、次のtime slice向けに最適化したmachine codeへ変える処理",
    "現在processを終了して同じexecutableから新processを作り、途中位置を引数で復元する処理",
    "heap上のobjectをCPUに近いaddressへ移動し、cache localityを改善してから実行を続ける処理",
  ],
  "l2-computer-interrupt": [
    "CPUがdevice状態を一定間隔でpollingし、変化を見つけるまで同じ確認処理を続ける仕組み",
    "複数threadによる同じ変数へのwriteをcompilerが検出し、buildを中断して通知する仕組み",
    "programの例外を検出したOSがmemoryを直前のsnapshotへ戻し、同じ命令を再実行する仕組み",
    "RAM不足を検知したruntimeが未使用objectを回収し、applicationへ空き容量を知らせる仕組み",
    "user操作をevent logへ保存し、障害後に同じ入力を再生して状態を復元する仕組み",
  ],
  "l2-design-dependency-injection": [
    "利用classがconcrete dependencyを内部でnewし、constructor引数を減らして呼び出し側から隠す手法",
    "package managerへlibrary名を登録し、必要versionをbuild時にdownloadするdependency管理",
    "依存objectをglobal singletonへ置き、すべてのmoduleが同じinstanceを直接参照する手法",
    "DI containerを導入した場合だけ成立し、constructorやfunction引数では実現できない手法",
    "interfaceを使わずruntimeのclass名を文字列で切り替え、型の依存関係をなくす手法",
  ],
  "l2-design-liskov-substitution": [
    "subclassは親の全methodをoverrideし、同じ処理を別実装へ置き換えるべきという原則",
    "method signatureが同じなら事前条件を強めたり新しい例外を投げたりしても置換可能という原則",
    "inheritance階層を三段以内に抑えれば、振る舞いの違いにかかわらず置換できるという原則",
    "基底classをabstractにしてinstance化を禁止すれば、自動的に契約を満たすという原則",
    "subclass固有methodを利用側が型判定して呼び分け、正しい実装を選択するという原則",
  ],
  "l2-design-interface-segregation": [
    "一つのinterfaceにはmethodを一つだけ置き、利用関係にかかわらず最小fileへ分ける原則",
    "実装classごとに専用interfaceを一つ作り、複数classで契約を共有しないという原則",
    "利用者ごとの小さなinterfaceを一つの大きな契約へ統合し、import数を減らす原則",
    "classのpublic methodをすべてinterfaceへ公開し、利用者が全機能へ依存できるようにする原則",
    "network interfaceをsegmentごとに分け、service間の通信経路を制限するinfra原則",
  ],
  "l2-design-layered-architecture": [
    "各layerが上下を自由に呼び合い、最短経路でdataへ到達できるようにするため",
    "UIからdatabase schemaを直接参照し、変換処理をなくしてlatencyを下げるため",
    "layer数を必ずpresentation・business・dataの三つへ固定し、構成差をなくすため",
    "下位layerが上位のconcrete classをimportし、変更をcallbackで即座に通知するため",
    "directory名とteam担当だけを揃え、runtimeのdependency方向は設計対象にしないため",
  ],
  "l2-design-stateless-scaling": [
    "sessionを各serverのmemoryへ保存すれば、同じuserを任意serverへ振り分けても処理できるから",
    "statelessにするとdatabaseやshared storageも不要になり、永続dataを持たずに済むから",
    "前回状態を持たなければauthenticationやauthorizationを各requestで省略できるから",
    "HTTPがserver stateを禁止しており、stateful serverはload balancerから拒否されるから",
    "stateless serverはcacheを持てないため、instance間で古いdataが混ざらなくなるから",
  ],
  "l2-network-three-way-handshake": [
    "client証明書・server証明書・共通鍵を三回送ってTLS暗号化を確立すること",
    "SYNを三つのnetwork経路へ送り、最初に到着したrouteをconnectionへ固定すること",
    "DNSをroot・TLD・authoritativeの三段へ問い合わせ、接続先IPを確認すること",
    "HTTP method・path・bodyを別packetで送り、serverが受理できる形式か確認すること",
    "双方のOSとTCP versionとapplication protocolを順番に交換し、互換性を調整すること",
  ],
  "l2-network-redirect-301-302": [
    "302が恒久移転、301が一時移転を表し、302だけをsearch engineが長期保存する",
    "301はrequest成功、302はserver errorを表し、Location headerの有無とは関係しない",
    "301はGET専用、302はPOST専用で、元のHTTP methodによってstatusを選ぶ",
    "301はserver内部だけで転送し、302の場合だけclientへ新URLを通知する",
    "どちらもDNS record変更をbrowserへ知らせるcodeで、HTTP resourceの場所は変えない",
  ],
  "l2-network-dns-record-types": [
    "A recordは別のdomain名、CNAMEはIPv4 addressへ直接対応づけるという関係",
    "A recordはIPv6 address、CNAMEはIPv4 addressだけを保存するaddress familyの違い",
    "A recordはmail server、CNAMEはweb serverだけに使うservice種類による違い",
    "CNAMEはresponseへ暗号署名を付け、A recordの改ざんを検出するsecurity record",
    "A recordにはTTLを設定できず、CNAMEを経由したresponseだけがcacheされるという違い",
  ],
  "l2-network-keep-alive": [
    "一つのHTTP/1.1 connectionで複数requestを常に同時実行し、responseを任意順で返すこと",
    "server processへ定期pingを送り、応答がなければOSがapplicationを再起動すること",
    "request bodyを圧縮して転送時間を短くし、connectionが生存する時間を延ばすこと",
    "requestごとに新しいconnectionを作り、同時接続数を増やしてthroughputを上げること",
    "session Cookieの期限をresponseごとに更新し、userのlogin状態を維持すること",
  ],
  "l2-security-jwt-structure": [
    "header・payload・signatureはすべて暗号化され、signatureがpayloadの秘密性を保証する",
    "headerとsignatureの二部構成で、user dataはserver側sessionにだけ保存する形式",
    "signatureが正しければtokenの失効・audience・有効期限も検証済みになる形式",
    "payloadへ秘密情報を入れても署名鍵がなければ読めないため、password保存にも使える形式",
    "serverがJWT本体をdatabaseへ保存し、signatureはrecord IDとの対応だけを保証する形式",
  ],
  "l2-security-digital-signature": [
    "送信者が公開鍵で署名を作り、受信者だけが秘密鍵で復号して作成者を確認する仕組み",
    "双方が共有する同じ秘密鍵で署名し、第三者も公開鍵で送信者を区別できる仕組み",
    "dataへhash値を添付するだけで、hashを作り直せる攻撃者からの改ざんも検出する仕組み",
    "認証局が通信内容を中継して毎回本人確認し、正規dataだけを受信者へ転送する仕組み",
    "IP addressとtimestampを署名欄へ入れ、DNS reverse lookupで送信元を証明する仕組み",
  ],
  "l2-security-same-origin-policy": [
    "異なるoriginへのrequest送信そのものをnetwork層で止め、serverへ到達させない仕組み",
    "同じdomainでも別tabからのJavaScript accessを禁止し、browser processを分離する仕組み",
    "HTTPSでないpageの通信をすべてblockし、暗号化済みoriginだけを許可する仕組み",
    "serverが許可したclient IP以外を拒否し、browser外のHTTP clientにも適用する仕組み",
    "host名だけが同じならschemeやportが異なっても同一originとしてdataを共有する仕組み",
  ],
  "l2-security-hsts": [
    "HTTP requestを受けたserverが毎回301を返し、最初の平文通信もredirectで安全に保護する仕組み",
    "browserが証明書の失効状態をCAへ問い合わせ、期限切れcertificateを自動更新する仕組み",
    "serverが古いTLS cipherだけを拒否し、HTTPで接続するかどうかはuserに選ばせる仕組み",
    "browserが全CookieへSecure属性を追加し、site側のheader設定なしで漏洩を防ぐ仕組み",
    "DNS responseへ署名を付け、偽IP addressへの名前解決を防ぐDNSSECと同じ仕組み",
  ],
  "l2-security-totp": [
    "serverが一定間隔でrandom codeを生成して端末へpushし、表示済みcodeをdatabaseで照合する",
    "端末が秘密鍵なしでrandom codeを作り、serverへ先に登録してからloginに使う",
    "認証のたびにappとserverが通信して新しい共通鍵を合意し、その場でcodeを作る",
    "登録時に将来使うcode一覧を端末へ保存し、上から順に一件ずつ消費する",
    "電話番号と現在時刻だけをhash化し、どのserviceでも同じuserなら同じcodeを作る",
  ],
  "l3-computer-cache-locality": [
    "同じdataは時間を空けるほど再利用されやすい時間局所性と、遠いaddressほど参照されやすい空間局所性",
    "すべてのmemory accessを一つのcache lineへ集め、CPU cacheの容量を超えないようにする考え方",
    "threadを複数coreへ頻繁に移動し、各coreのcacheへ同じdataを複製してhit率を上げる考え方",
    "random accessを増やしてhardware prefetchを無効化し、古いcache entryを早く追い出す性質",
    "disk上で近いfileをまとめる性質だけを指し、CPUのinstructionやdata cacheには関係しない",
  ],
  "l3-computer-virtual-memory": [
    "全processが同じphysical addressを直接参照し、application側のIDで互いの領域を区別する仕組み",
    "RAM不足時に全memoryをdiskへ移し、物理memoryを使わずstorageだけでprocessを動かす仕組み",
    "processごとに実容量と同じ連続physical memoryを予約し、address変換を行わない仕組み",
    "CPU cacheをapplicationへ大きなmemoryとして見せ、OSを介さず直接管理させる仕組み",
    "複数machineのRAMをnetwork経由で一つに見せ、local memoryとして透過利用する仕組み",
  ],
  "l3-network-tls-handshake": [
    "clientのpasswordをserverへ送り、application loginと通信暗号化を一度に完了すること",
    "DNSから取得した公開鍵でserverを検証し、CAや証明書chainを使わず接続先を確認すること",
    "以後の全dataを公開鍵暗号だけで送るため、serverの秘密鍵そのものをclientへ安全に渡すこと",
    "HTTP methodとstatus codeを合意し、両者が対応するprotocol versionを選択すること",
    "network経路上のrouterを認証し、packetが同じrouteを通るように固定すること",
  ],
  "l3-security-threat-asset": [
    "利用するsecurity製品を先に選び、その製品で防げない攻撃だけを脅威として列挙すること",
    "既知の脆弱性一覧をすべて修正してから、守るdataやbusiness impactを確認すること",
    "攻撃者の種類を一つに固定し、内部者や自動化botなど別の主体は運用段階で扱うこと",
    "system構成図のcomponent数を数え、数が多い箇所から均等に対策costを配分すること",
    "発生可能性にかかわらず全脅威を同じ優先度にし、同時に完全対策する計画を作ること",
  ],
  "l3-design-acid": [
    "Availability、Consistency、Isolation、Distributionで、分散systemの可用性と配置を表す",
    "Atomicity、Concurrency、Integrity、Dependencyで、並行処理とmodule依存を表す",
    "Authentication、Confidentiality、Integrity、Durabilityで、transactionのsecurityを表す",
    "Atomicity、Consistency、Idempotency、Deliveryで、message queueの配送保証を表す",
    "Availability、Caching、Isolation、Durabilityで、database performanceの性質を表す",
  ],
  "l3-computer-file-descriptor": [
    "system全体で一意なfile pathを整数化し、別processでも同じ番号なら同じfileを指す識別子",
    "storage上のblock addressを直接表し、applicationがfilesystemを介さず読み書きする番号",
    "開いているregular fileだけを指し、socket・pipe・deviceには使われないprocess内識別子",
    "file内容のhash値を短い整数にしたもので、同じ内容のfileは同じ番号になる識別子",
    "OSがuserごとのアクセス権を表す番号で、read/write permissionそのものを保持する識別子",
  ],
  "l3-design-cqrs": [
    "更新と参照を同じmodelへ統合し、どのoperationも同じrepository methodで処理する設計",
    "commandを同期HTTP、queryを非同期queueへ固定し、transport方式で責務を分ける設計",
    "write databaseとread databaseを物理的に分けることだけを指し、modelは共通に保つ設計",
    "すべての更新をeventとして永久保存するEvent Sourcingと同じ意味で、単独では使えない設計",
    "更新結果がread側へ反映されるまでrequestをblockし、常にstrong consistencyを保証する設計",
  ],
  "l3-network-websocket": [
    "requestごとに新しいTCP connectionを張り、serverからの通知はclientのpollingで受け取る方式",
    "HTTP responseを閉じずにserverからだけdataを送り続け、clientから追加messageは送れない方式",
    "UDP上でpacket再送を行わず、順序保証より低latencyを優先するdatagram protocol",
    "browser同士がserverを介さず直接接続し、常にpeer-to-peerで通信するAPI",
    "HTTP/2の各requestをWebSocket frameへ変換し、connectionを使い回さず多重化する方式",
  ],
  "l3-network-http2-multiplexing": [
    "一つのrequestが完了するまで同じconnectionの後続requestを送らず、順序を守る方式",
    "複数のTCP connectionを同時に作り、各connectionへ一つずつrequestを割り当てる方式",
    "一つのstreamでpacket lossが起きてもTCP層で他streamは停止せず、独立に届く方式",
    "serverからclientへのresponseだけを並行化し、client requestは一件ずつ送る方式",
    "複数hostへのrequestを同じconnectionへ常に統合し、証明書や接続先を区別しない方式",
  ],
  "l3-security-clickjacking": [
    "正規pageへscriptを注入してbuttonのclick handlerを書き換え、CSP script-srcだけで防ぐ攻撃",
    "偽login pageへuserを誘導してpasswordを入力させ、SameSite Cookieで防ぐphishing攻撃",
    "透明な要素で正規pageの見た目を再現するが、正規page自体はframeへ読み込まない攻撃",
    "別siteから状態変更requestを送らせるCSRFで、anti-CSRF tokenだけが基本対策となる攻撃",
    "pointer位置を推測してbrowser外のapplicationを操作し、X-Content-Type-Optionsで防ぐ攻撃",
  ],
  "l4-computer-gc": [
    "参照が残っていても使用時刻が古いobjectはGCが不要と判断し、自動的に回収できるから",
    "GCはheap容量が不足した時だけ動くため、容量を増やせば参照保持によるmemory増加も止まるから",
    "循環参照は到達可能性に関係なく回収できないので、すべてのcycleを手動で切る必要があるから",
    "memory leakとは解放済みaddressへ再アクセスする問題で、参照が残るobjectの増加とは異なるから",
    "GCはapplicationが作ったobjectだけを回収し、listenerやcacheが保持する参照は検査しないから",
  ],
  "l4-computer-backpressure": [
    "下流の処理量を超えたdataを上流に関係なくmemoryへ貯め、欠落せず後で処理する仕組み",
    "下流が遅い時にconsumer数だけを増やし、producerの生成速度は維持するautoscaling戦略",
    "queueが上限へ達したら古いdataを無条件に削除し、上流へ状態を通知しないdrop policy",
    "上流が一定rateで送り続けられるよう、下流のtimeoutを延長して待ち時間を隠す仕組み",
    "network congestionだけを検知してTCP windowを調整し、application queueは対象にしない制御",
  ],
  "l4-network-head-of-line": [
    "後続処理のpriorityが高いと先頭処理を追い越すため、response順が入れ替わる問題",
    "複数の独立connectionが同時に帯域を使い、公平に分配されず一部が速くなる問題",
    "queue末尾の処理が長いことで、すでに開始した先頭処理まで完了できなくなる問題",
    "packetが順番通り届いた場合にbufferが溢れ、先頭packetだけを破棄するflow control問題",
    "HTTP request headerが大きいためbodyの読み込み開始が遅れ、header圧縮でだけ解決する問題",
  ],
  "l4-security-ssrf": [
    "攻撃者のbrowserからinternal APIへ直接requestを送り、CORS responseを読めない問題",
    "serverのresponseへscriptを注入し、閲覧userの権限で外部URLへrequestさせる攻撃",
    "user指定redirect URLへbrowserを移動させ、偽siteへ誘導するopen redirect攻撃",
    "Host headerを改ざんしてpassword reset linkへ攻撃者domainを混入させる攻撃",
    "DNS cacheへ偽responseを保存し、全userを攻撃者serverへroutingする攻撃",
  ],
  "l4-design-slo-sli": [
    "SLIは達成したい信頼性の目標値、SLOはその目標を測るrequest latencyなどの実測値",
    "SLIは顧客との法的な補償契約、SLOは違反時の返金条件を定めるservice agreement",
    "SLIはsystem内部の全metric、SLOは収集したmetricを保存するobservability platform",
    "SLIは障害が許されるerror budget、SLOはbudgetを使い切った後のrelease停止規則",
    "SLIとSLOは同じ目標を内外で呼び分けた名称で、指標と目標値を区別しない",
  ],
  "l4-computer-mmap": [
    "file全体をkernel bufferへreadしてからheapへcopyし、通常のread回数を一回に減らす方式",
    "physical memory addressへfile blockを固定し、page faultやOS cacheを介さずaccessする方式",
    "fileをprocess間で共有すると書き込みが自動transaction化され、競合更新を直列化する方式",
    "mapping作成時にfile全体がRAMへ読み込まれるため、access時のI/Oが発生しない方式",
    "memory内容を暗号化してfileへ保存し、process終了時に自動復号するsecurity機能",
  ],
  "l4-design-feature-flag": [
    "機能ごとに別branchを長期間維持し、release時に対象branchをmainへmergeする仕組み",
    "deploy済みcodeを変更せず切り替えられるため、古いflagや分岐を恒久的に残す設計",
    "flagを有効化すればdatabase migrationや外部dependencyも同時に原子的切替できる仕組み",
    "test環境だけで機能を有効化し、本番ではrelease判断に使えないbuild-time設定",
    "userごとの権限をflag名で表し、authorization checkの代わりに機能表示を制御する仕組み",
  ],
  "l4-network-load-balancing-algorithm": [
    "各serverのactive connection数を測り、最も少ないserverへ次requestを送る方式",
    "client IPのhash値からserverを選び、同じclientを同じserverへ固定する方式",
    "response timeの移動平均を比べ、最もlatencyが小さいserverへ優先して送る方式",
    "serverごとのCPUやqueue長に応じてweightを変え、余力のあるserverへ多く送る方式",
    "randomに二台を選んで負荷を比較し、軽い方へrequestを送るpower-of-two方式",
  ],
  "l4-network-connection-pooling": [
    "requestごとに新しいconnectionを確立し、終了後すぐ閉じて古いstateを残さないため",
    "一つのconnectionを全requestで同時利用し、protocolの多重化可否にかかわらず順序を無視するため",
    "pool上限をなくしてtrafficに応じたconnectionを作り、待ち時間を発生させないため",
    "server側のtransaction stateをpoolへ保存し、別requestが前のtransactionを継続するため",
    "DNS lookup結果をconnectionへ固定し、接続先変更後も古いserverだけを使い続けるため",
  ],
  "l4-security-csp": [
    "response内の危険なscriptをserver側で解析・削除し、安全なJavaScriptだけへ書き換える",
    "CookieへHttpOnlyを付けてscriptから読めなくし、script自体の実行元は制限しない",
    "入力値のHTML tagをすべて禁止し、出力contextにかかわらずcode実行を防ぐ",
    "TLSでresponse改ざんを防げばinline scriptも安全とみなし、外部sourceだけを制限する",
    "違反したscriptをreportするだけでbrowser実行も停止するため、Report-Onlyで強制防御する",
  ],
  "l5-computer-mvcc": [
    "全transactionが同じ最新版だけをreadし、更新中のrowにはreaderも排他lockを取る制御方式",
    "rowごとに一つのversion番号だけを保持し、番号不一致のtransactionを即座にrollbackする方式",
    "複数replicaへ同じdataをcopyし、node障害時のread可用性を高めるreplication方式",
    "古いversionを永久保存して任意時点へ復元できるbackup方式で、transaction分離とは独立した仕組み",
    "write transactionを一件ずつ実行し、readとwriteの並行実行自体を禁止するpessimistic制御",
  ],
  "l5-computer-btree": [
    "keyをhash bucketへ均等配置し、range scanより完全一致検索だけを一定時間で行えるから",
    "全entryを一つの連続配列に保ち、insert時の全要素移動と引き換えにbinary searchできるから",
    "頻出keyをrootへ移動する自己調整木で、access patternに応じて常に最短経路を作るから",
    "leafをmemoryだけに置きinternal nodeをdiskへ置くことで、write時のI/Oをなくせるから",
    "treeを一方向へ伸ばして時系列順を保ち、rebalanceを行わずappendだけで更新できるから",
  ],
  "l5-network-consensus-quorum": [
    "全nodeから応答を待って同じ値なら成功とするため、一台の障害でも更新を停止して整合性を守る",
    "最初に返った一台の値を採用し、残りnodeの応答は遅延を避けるため結果へ使わない方式",
    "読取り数Rと書込み数Wの合計に関係なく、それぞれ一台以上なら最新値を必ず共有できる方式",
    "過半数へ到達できないpartition側もlocal majorityとして更新を続け、復旧後に時刻で統合する方式",
    "投票数だけでByzantineな応答も正しい値と判定でき、署名やfault modelを考えず合意する方式",
  ],
  "l5-security-oauth-oidc": [
    "OAuth 2.0は本人確認、OpenID ConnectはAPI操作のscope委譲だけを扱うという役割分担",
    "OAuth access tokenの中身をclientが読めばuser identityを確認できるため、ID tokenは不要という関係",
    "OpenID ConnectはOAuthと独立したpassword認証protocolで、authorization endpointを共有しない",
    "OAuth 2.0はserver間通信専用、OpenID Connectはbrowser login専用という利用環境の違い",
    "OpenID Connectを使えばAPI側のauthorizationも完了し、resourceごとの権限確認は不要になる",
  ],
  "l5-design-cap-pacelc": [
    "CAPは平常時のlatencyとconsistency、PACELCはpartition時のavailabilityだけを扱う分類",
    "CAPは三特性から平常時に二つを選び、network partitionを起こさない設計なら三つとも保証できる理論",
    "PACELCはpartition発生時にもlatencyとconsistencyだけを選び、availabilityは常に維持する考え方",
    "CAPのconsistencyはACIDのConsistencyと同じ業務制約を指し、linearizable readとは関係しない",
    "PACELCのELは障害時の選択、PCは平常時の選択を表し、CAPと反対の順序で判断する",
  ],
  "l5-computer-copy-on-write": [
    "fork時に親の全pageを子へcopyし、書込みがなかったpageだけ終了時に共有へ戻す仕組み",
    "親が書込む時だけpageをcopyし、子が書込む場合は親のpageをそのまま更新する仕組み",
    "親子が同じphysical pageへ自由に書込み、競合した値をOSがtimestamp順にmergeする仕組み",
    "page tableではなくfile descriptorだけを複製し、heapとstackはfork後も同じ領域を使う仕組み",
    "read accessのたびにpageをprocess固有へcopyし、他processから内容を観測できなくする仕組み",
  ],
  "l5-design-backpressure": [
    "consumerの遅れを検知したらproducerのdataを無制限bufferへ退避し、送信rateを維持する仕組み",
    "流入量が増えたらconsumerをscale outするだけで、上流への拒否や待機を行わない仕組み",
    "queue上限時に新しいmessageを黙ってdropし、producerへ成功responseを返すoverflow policy",
    "producerが固定rateを保てるようconsumer timeoutを延ばし、処理待ち件数を隠す仕組み",
    "system全体の平均throughputが足りていれば局所的なqueue増加を許容し、制御しない設計",
  ],
  "l5-network-grpc-http2": [
    "HTTP/2がUDP上でpacket lossをstreamごとに分離するため、transport層のHead-of-Line blockingも避けられるから",
    "HTTP/2がJSON schemaを自動生成し、Protocol Buffersなしで型付きmessageを作れるから",
    "一つのTCP connectionにつき一つのRPCへ制限し、RPCごとの順序とresourceを分離できるから",
    "browserのsame-origin policyを回避し、CORS設定なしで任意originからRPCを呼べるから",
    "HTTP/1.1ではTLSを使えないため、HTTP/2で暗号化とclient認証を同時に得られるから",
  ],
  "l5-network-failover-strategy": [
    "active nodeの負荷が上がるたびstandbyへ一部trafficを分散し、両nodeを常時activeにする仕組み",
    "standbyがactiveのhealthを自己判断して昇格し、fencingなしでも二重activeを避けられる仕組み",
    "障害を検知したclientが各自でstandbyのaddressへ変更し、共有の切替判断を持たない仕組み",
    "activeのapplication processだけを再起動し、dataやnetwork endpointは切り替えない復旧操作",
    "障害中のrequestをすべて保存してactive復旧後に再生し、standbyはreadだけを行う仕組み",
  ],
  "l5-security-cors-misconfig": [
    "wildcard originとcredentialsを指定すればbrowserがcredential送信だけを拒否するため、response公開の危険はない",
    "requestのOriginをそのままallow listへ反射してもcredentialsを許可しなければ、token付きAPIを含め安全である",
    "CORSはrequestがserverへ届く前にnetworkで遮断するため、state-changing APIのCSRF対策も兼ねられる",
    "trusted originのsuffix一致だけを確認すれば、evil-example.comのようなdomainはbrowserが自動的に除外する",
    "preflightへ正しいheaderを返せばresponseのcache keyへOriginを含めなくても、CDNで別originへ混ざらない",
  ],
  "l6-computer-scheduler": [
    "schedulerはprocess間の優先度だけを決め、同一process内のkernel threadはruntimeだけが切り替える",
    "context switchでは汎用registerだけを退避し、address spaceやTLB、cache localityへの影響は生じない",
    "preemptive schedulerはtaskが自発的にyieldした時だけ切り替えるため、長い計算があれば他taskは動けない",
    "event loopを使うprocessでは実行taskが一つなので、process自体に対するOS schedulingは発生しない",
    "thread数をCPU core数より増やすと待ち時間を隠せるため、switch costにかかわらずthroughputは上がる",
  ],
  "l6-computer-tlb-pagefault": [
    "TLB missとpage faultは同じ事象であり、どちらも対象pageをdiskから読み込むまでprocessを停止する",
    "TLBはvirtual addressからfile offsetへの対応を保持し、page tableは物理pageの内容そのものをcacheする",
    "minor page faultでもstorage I/Oが必要で、major page faultとの違いは割り込みpriorityだけにある",
    "TLB entryをinvalidateすれば物理pageも解放されるため、page tableを更新する処理は必要ない",
    "huge pageを使うとTLB missとpage faultの両方がなくなり、memory accessは物理addressと同じcostになる",
  ],
  "l6-computer-endianness": [
    "little endianは各byte内のbitを下位から並べ、big endianはbitを上位から並べる規約である",
    "network byte orderは接続相手のCPU endianに合わせてhandshakeごとにlittle/bigを選択する",
    "endiannessは文字列の文字順にも適用されるため、UTF-8文字列はCPUごとに逆順へ並べ替える",
    "compilerが型情報から変換するので、binary protocolやfile formatではbyte orderを明記しなくてよい",
    "複数byte値には保存時のendian情報が付くため、別endianのCPUでも同じbyte列をそのまま解釈できる",
  ],
  "l6-network-tcp-congestion": [
    "受信側が処理可能なbuffer量をadvertised windowで通知し、送信側のoverflowを防ぐflow controlのこと",
    "connectionごとのpacket順序を保証するため、欠落segmentが再送されるまで後続dataをアプリへ渡さないこと",
    "RTTにかかわらず固定rateで送り、packet lossが起きたconnectionだけを切断してnetwork負荷を下げること",
    "receiver側のCPU使用率をTCP headerへ載せ、application処理能力に合わせてcongestion windowを決めること",
    "routerが全connectionへ同じ帯域を割り当てる仕組みで、endpoint側は送信量を調整しないこと",
  ],
  "l6-network-dns-rebinding": [
    "攻撃者が偽のDNS responseへ署名し、DNSSEC検証を突破して被害者domainのaddressを書き換える攻撃",
    "短いTTLによってbrowserのsame-origin判定も更新され、同じhost名が別originとして扱われなくなる問題",
    "CORS preflightを省略できる単純requestだけを使い、異なる攻撃者domainから内部APIのresponseを読む攻撃",
    "Host headerを内部IPへ直接変更し、DNS lookupを行わずにbrowserをprivate networkへ接続させる攻撃",
    "public IPとprivate IPを同じTLS証明書へ登録し、証明書検証に成功すれば内部serviceへ到達できる問題",
  ],
  "l6-security-deserialization": [
    "JSON文字列をobjectへ変換するとproperty値がcodeとして評価されるため、primitiveだけのJSONにもRCEが生じる",
    "暗号化されたserialized dataを復号すると型情報が失われ、別classとして復元されることで権限が上がる",
    "入力schemaを検証すれば復元時に呼ばれるconstructorやgadget chainも検査されるため、型制限は必要ない",
    "署名付きpayloadなら内容を作った主体を確認できるので、漏洩した署名鍵や古い危険objectも安全に復元できる",
    "deserializationの危険はobject sizeによるDoSに限られ、復元処理からmethod実行へ到達することはない",
  ],
  "l6-security-prototype-pollution": [
    "攻撃者がinstanceのown propertyを変更するだけの問題で、同じprototypeを使う別objectへは伝播しない",
    "class構文で継承したobjectに限って発生し、object literalやdeep merge utilityは影響を受けない",
    "Object.freezeで入力objectを凍結すれば、merge先のObject.prototypeへ書き込まれても影響を防げる",
    "JSON.parseが__proto__ keyを読む時点で必ずglobal prototypeを書き換えるため、後続のmerge処理は関係ない",
    "汚染されたpropertyは画面表示だけに影響し、authorization flagやcommand optionへ使われることはない",
  ],
  "l6-design-eventual-consistency": [
    "同じuserを一つのreplicaへ固定すればread-your-writesに加えて、他userとの更新順序もglobalに保証できる",
    "replication lagの上限を短く設定すれば、その時間内でも古い値を返さないstrong consistencyとして扱える",
    "last-write-winsを使えば同時更新を失わずmergeできるため、競合内容をuserへ見せる設計は必要ない",
    "在庫や権限の判定も最終的に収束すればよく、古いreadによる一時的な二重販売や過剰権限は許容できる",
    "書き込み直後だけprimaryへ読みを送れば、その後のsessionでreplicaが巻き戻った値を返すことはない",
  ],
  "l6-design-outbox": [
    "DBをcommitしてからbrokerへpublishし、送信失敗時はapplication logを見て手動再送する設計",
    "brokerへのpublish成功後に業務DBを更新し、DB失敗時はconsumerへ取消eventを必ず送る設計",
    "outbox rowを作ればbrokerとconsumerを含むend-to-end exactly-onceが保証され、冪等処理は不要になる",
    "relayがeventを送る前にoutbox rowを送信済みに更新し、crash時の重複より欠落を優先する設計",
    "CDCでtransaction logを読めばevent順序や重複が自動解決されるため、aggregate IDやsequenceを持たない設計",
  ],
  "l6-design-ddd-boundary": [
    "一つのbounded contextを一つのdeploy unitへ対応させる規則で、modelの意味よりservice数から境界を決める",
    "全contextで共通のCustomer entityを共有し、営業・請求ごとの意味の違いはnullable fieldで吸収する",
    "database transactionを跨がない範囲を表すため、同じDBを使うmoduleは同じcontextへ統合する",
    "teamの担当範囲を示す組織図であり、context間のmodel変換や契約はarchitectureの対象にしない",
    "同じ用語をcontextごとに別の意味で使うと混乱するため、全社共通の唯一のmodelへ統一する考え方",
  ],
  "l6-network-bgp-anycast": [
    "DNSがclientの緯度経度から一つのIPを選び、そのIPを特定PoPだけがunicast広告する方式",
    "同じIPへのpacketを全PoPへ複製し、最初に返ったresponseだけをclientが採用する方式",
    "BGPのAS pathが短い経路は物理距離とlatencyも最小なので、常に地理的に最寄りのPoPへ到達する方式",
    "一度確立したTCP connectionを経路変更時に別PoPへ状態ごと移送し、sessionを継続させる方式",
    "network経路だけでapplication dataも同期されるため、どのPoPへ到達してもsession stateが揃う方式",
  ],
  "l6-computer-memory-barrier": [
    "compilerによる命令並べ替えだけを止める構文で、CPUのout-of-order実行やstore bufferには影響しない",
    "barrier以前の全cache lineをmain memoryへ書き戻し、他coreがDRAMから読むことを保証する命令",
    "cache coherenceが同じaddressの値を揃えるため、異なるaddress間の観測順序にもbarrierは必要ない",
    "atomicな変数を一つ使えば周辺の通常memory accessも順序指定に関係なく同期されるという仕組み",
    "read barrierとwrite barrierは全architectureで同じ強さを持ち、acquire/releaseを区別しない命令",
  ],
  "l6-computer-cache-coherence": [
    "各coreが異なるaddressへのload/storeを同じ順序で観測するmemory consistency modelそのもの",
    "L1 cacheとmain memoryの内容を各命令後に同期し、すべてのcoreが常にDRAMを正本として読む仕組み",
    "同じcache line上の別変数をcoreごとに更新すると値が論理的に矛盾するfalse sharingだけを指す問題",
    "compilerがregisterへ保持した値を他threadへ公開するための規則で、hardware cache protocolとは独立した問題",
    "write-through cacheを採用すればcore間のinvalidateやownership移動が不要になり、coherence問題は消える",
  ],
  "l6-design-circuit-breaker": [
    "依存先の失敗時に一定回数まで即時retryし、成功するまでrequestを同じworkerへ保持する仕組み",
    "依存先ごとにthread poolを分離し、一つの遅延が他機能のresourceを占有しないようにする仕組み",
    "単位時間あたりのrequest数を制限し、上限を超えたclientへ429を返してserviceを守る仕組み",
    "health checkで異常instanceをload balancerから外し、正常instanceだけへroutingする仕組み",
    "呼び出しごとに短いtimeoutを設定し、期限を超えた単発requestだけをcancelする仕組み",
  ],
  "l6-design-bulkhead": [
    "失敗率が閾値を超えた依存先への呼び出しをopen状態で遮断し、回復後にhalf-openで試す設計",
    "全処理で共有するpoolへpriority queueを置き、重要requestを先に処理して容量自体は分けない設計",
    "負荷に応じてinstance数を増やし、同じresource poolを全機能で共有したままcapacityを足す設計",
    "依存先への同時接続数をservice全体で一つに制限し、機能ごとの利用枠は分けない設計",
    "障害時にfallback responseを返して機能を縮退させるが、threadやconnectionの隔離は行わない設計",
  ],
  "l6-network-quic-http3": [
    "UDP自体がpacket再送と順序保証を持つため、QUICはTCP相当の信頼性処理を実装せずに済むから",
    "HTTP/2のapplication stream間だけでなく、QUIC connection内でも一つのpacket lossが全streamを停止させるから",
    "TLSをtransportから分離して任意に省略でき、暗号化しない接続でhandshakeを短縮できるから",
    "kernelのTCP実装を使うことでOS更新なしにtransport機能を変更しやすく、user space実装を避けられるから",
    "NATやfirewallがUDPをTCPより一貫して許可するため、接続失敗時のfallbackを考えなくてよいから",
  ],
  "l6-network-congestion-control-algorithms": [
    "RTTの増加や推定帯域を使わずpacket lossだけをcongestion signalとしてwindowを増減させる方式",
    "receiver advertised windowを帯域幅として扱い、受信bufferが空く速度だけからpacing rateを決める方式",
    "一度測定したbandwidth-delay productをconnection終了まで固定し、経路変化による再推定を行わない方式",
    "packet lossが観測されない経路では送信rateを上げ続け、queue delayをCUBICより大きくする方式",
    "routerから各flowの公平な帯域割当を通知してもらい、その値をcongestion windowへ直接設定する方式",
  ],
  "l6-security-supply-chain": [
    "SBOMが依存componentを列挙すれば改ざん済みpackageの実行も防げるため、署名やbuild provenanceは不要になる",
    "source repositoryのdirect dependencyだけを記録し、transitive dependencyやbuild toolは対象外とする台帳",
    "既知CVEと修正版だけを配布する脆弱性databaseで、製品が実際に含むcomponentの一覧は保持しない",
    "artifactへ署名があれば署名者のbuild環境も侵害されていないと分かるため、生成過程を追跡しない方式",
    "本番でloadされたlibraryを実行時に一覧化する監視方式だけを指し、release前の影響調査には使わない",
  ],
  "l6-security-timing-attack": [
    "秘密値をhash化してから通常の早期終了比較を行えば、比較位置による時間差は入力へ現れない",
    "network jitterが処理時間差より大きければ統計的な反復測定でもsignalを抽出できず、remote攻撃は成立しない",
    "比較前にrandomなsleepを加えれば分布が完全に隠れるため、constant-time実装へ変更する必要はない",
    "constant-time比較とはrequest全体を固定時間で返すことで、比較対象のlength差は先に返してよい実装である",
    "rate limitを設定すれば秘密に依存する時間差自体がなくなるため、比較関数の実装は通常のままでよい",
  ],
  "l6-security-injection-types": [
    "Path Traversal(../を含む入力で、許可directoryの外にあるfileを読み書きさせる攻撃)",
    "Unsafe Deserialization(細工したserialized objectの復元時に、gadget chainを実行させる攻撃)",
    "SSRF(user指定URLをserverに取得させ、internal networkやmetadata endpointへ到達する攻撃)",
    "Session Fixation(攻撃者が用意したsession IDを、被害者のlogin後も継続利用させる攻撃)",
    "Credential Stuffing(他serviceから漏洩したIDとpasswordの組をlogin APIへ試す攻撃)",
  ],
  "l7-computer-linearizability": [
    "全操作に単一の順序が存在すれば、実際の完了順と開始順が逆転していてもlinearizableとみなせる",
    "並行トランザクションの結果が何らかの直列実行と等価なら、個々の操作の実時間順序も保証される",
    "因果関係のある操作だけ同じ順序で観測できれば、無関係な操作の観測順が異なっても条件を満たす",
    "各クライアントが自分の書き込みを直後に読めれば、他クライアントが古い値を読んでも条件を満たす",
    "読み書きを過半数のレプリカへ送れば、レプリカ構成や障害時の処理によらず自動的に保証される",
  ],
  "l7-computer-serializability": [
    "各トランザクションが同じスナップショットを読めれば、write skewが起きても直列実行と等価になる",
    "コミット順が実時間の完了順と一致することまで要求するため、strict serializabilityとの差はない",
    "トランザクションを物理的に一つずつ実行する方式だけを指し、並行実行で達成することはできない",
    "コミット済みデータが障害後も残ることを保証する性質で、分離レベルや実行順序とは独立している",
    "同じ行への競合書き込みだけを直列化すれば、範囲条件を使う読み書きも常に条件を満たす",
  ],
  "l7-network-raft": [
    "leaderがログを受理した時点でcommitし、過半数への複製は障害復旧時に非同期で行う合意方式",
    "各ノードが書き込みを受理し、競合時は物理タイムスタンプが最大の値を残すことで合意する方式",
    "各termでは応答遅延が最小のノードをleaderに選び、過半数の投票なしで選出を確定する方式",
    "過半数へ複製済みでもleader交代時には自由に上書きでき、最新leaderのローカルログを正とする方式",
    "leaderからの読み取りは任期確認なしでも常に最新なので、分断後の古いleaderも安全に応答できる",
  ],
  "l7-network-vector-clock": [
    "各イベントへ単一の連番を付け、番号の大小だけで因果関係と並行関係の両方を完全に判定する時計",
    "NTPで同期した物理時刻をノードごとに保持し、タイムスタンプが同じ更新を並行と判定する時計",
    "競合更新では最も大きい成分を持つ値を常に採用し、もう一方を自動的に破棄する解決方式",
    "二つのベクトルは必ず大小比較できるため、全イベントへ因果関係を保つ全順序を与える論理時計",
    "クラスタ参加数が変わっても固定長の一要素だけを保持し、ノード識別なしで因果関係を表す時計",
  ],
  "l7-security-capability": [
    "主体IDに紐づく権限表を認可サーバで毎回検索し、権限を表す参照自体は主体へ渡さない方式",
    "署名されたbearer tokenには主体IDだけを入れ、対象資源への権限は別のglobal ACLで判定する方式",
    "権限をグローバルなロール名へ集約し、委譲先にも元の主体と同じロール一式を付与する方式",
    "capabilityが推測困難なら漏洩後も安全なので、期限・失効・再委譲の制約を持たせない方式",
    "capabilityの所持だけを記録し、誰から誰へ委譲されたかや実際の利用主体は監査しない方式",
  ],
  "l7-security-confused-deputy": [
    "攻撃者がサービス用の秘密鍵を盗み、その資格情報を使って保護APIを直接呼び出す認証情報漏洩",
    "呼び出し元が対象操作だけの委譲capabilityを渡し、サービスがその範囲内で処理する権限委譲",
    "ネットワークACLの設定ミスにより、保護されるべき管理APIへ攻撃者が直接接続できる公開設定",
    "共有オブジェクトを更新中に別スレッドが状態を変え、検査時と使用時の条件がずれる競合問題",
    "APIが対象リソースの所有者確認を行わず、利用者自身の権限で他テナントのデータを返すBOLA",
  ],
  "l7-design-saga": [
    "単一coordinatorが全参加サービスのprepare後に一斉commitし、途中失敗なら全変更を原子的に破棄する",
    "各サービスのイベント発行だけをoutboxへ保存すれば、後続処理の失敗時も補償なしで全体が元に戻る",
    "一時障害と業務エラーを区別せず成功するまで再試行し、完了済み処理は取り消さない設計",
    "途中のローカルトランザクションが失敗すると、先にcommitした別サービスの変更も自動rollbackされる",
    "補償処理は常に過去の状態をビット単位で復元する逆操作であり、返金など意味的な取消は含まない",
  ],
  "l7-design-crdt": [
    "全更新を中央サーバの同じ順序へ変換してから適用し、その順序に従えないオフライン更新は拒否する型",
    "任意のオブジェクトへ更新時刻を付け、常に最新時刻の状態を残せば更新損失なく収束できるデータ型",
    "通常の可変データを各レプリカで更新し、到着順に差分を再生するだけで自動的に収束するデータ型",
    "state-based CRDTではmergeが可換でさえあればよく、結合則や冪等性を満たさなくても収束する",
    "レプリカの収束と同時に、残高が負にならないなど任意の業務不変条件まで自動的に保証する仕組み",
  ],
  "l7-design-queue-semantics": [
    "brokerがexactly-once配送を宣言すれば、DB更新や外部APIを含む受け手の副作用にも重複対策は不要になる",
    "業務処理をcommitする前にackを返し、失敗時は同じメッセージが再配送されないようにすること",
    "メッセージの生成時刻だけで重複を判定し、同時刻のイベントは同じ処理として一件だけ残すこと",
    "検証エラーなど恒久的な失敗もackせず無制限に再配送し、成功するまでキューへ戻し続けること",
    "処理済みIDをDBへ保存すれば、DB外の通知送信との間に障害が起きても二重送信を防げること",
  ],
  "l7-security-zero-trust": [
    "サービス間をmTLSにすれば通信主体は判別できるため、操作ごとの認可や端末状態の評価を省略する",
    "社内IPかつ管理端末からのアクセスは一度だけ検証し、そのセッション中は権限変更を反映しない",
    "継続的検証とは全リクエストで利用者へ対話的な再ログインを要求し、セッションを保持しないこと",
    "ネットワークを細かく分割して到達経路を制限すれば、アプリケーション層の最小権限は不要になる",
    "職種ごとに広い固定ロールを付け、未使用権限も将来必要になる前提で継続して許可する考え方",
  ],
  "l7-network-backend-timeout-budget": [
    "直列に呼ぶ各下流へクライアントの期限と同じtimeoutを設定し、どの処理にも成功機会を等しく与える",
    "並列呼び出しでは各下流timeoutの合計だけを全体期限に収めれば、応答集約の時間は考慮しなくてよい",
    "最初の試行と再試行へ同じtimeoutを割り当て、再試行開始時の残り時間にかかわらず最後まで待つ",
    "通常時のp99をそのまま各timeoutに設定すれば、待ち行列や障害時の遅延を含む設計として十分である",
    "上流から下流へ進むほど長いtimeoutを設定し、下流が完了するまで上流の期限切れ後も処理を続ける",
  ],
  "l7-computer-lock-free": [
    "競合時にCASを再試行すれば、全スレッドが有限回で成功する公平性とstarvation freedomも保証される",
    "一回のCASで関連する複数メモリ位置をまとめて比較・更新し、複合状態を常に原子的に変更できる",
    "期待値が一致しない場合はOSがスレッドを待機させ、値を変更したスレッドの解放通知を待つ命令",
    "CASは全アーキテクチャで常にfull memory fenceとして働くため、追加のメモリ順序指定は不要である",
    "値がAからBを経てAへ戻るABA問題もCASが履歴を検出するため、version付与などの対策は不要である",
  ],
  "l7-computer-numa": [
    "first-touchで一度配置すれば、その後スレッドを別ノードへ移してもメモリは自動で常に最寄りへ追従する",
    "全ページを全NUMAノードへ均等interleaveすれば、局所性の高い処理でも常に最低latencyを得られる",
    "スレッドを特定CPUへpinすれば十分で、割り当て済みページのノードやI/O配置は性能へ影響しない",
    "remote memoryは帯域幅だけが低下しlatencyはlocal memoryと同じなので、小さいランダムアクセスは無関係である",
    "共有heapを使うGCではオブジェクト配置をruntimeが管理するため、NUMAを意識したheap設計は不要である",
  ],
  "l7-computer-branch-prediction": [
    "予測ミスは分岐命令の完了だけを遅らせ、後続の投機実行済み命令はそのままcommitできる",
    "誤った経路の命令が更新したレジスタとメモリはarchitectural stateへ残り、OSが後から巻き戻す",
    "条件が実行時データに依存していても、最適化compilerが全分岐を事前解決するためpenaltyは発生しない",
    "予測ミスのcostはpipelineの深さや実行幅に関係なく、どのCPUでも常に一cycleに固定されている",
    "条件分岐をbranchless表現へ置き換えれば追加命令や依存関係にかかわらず、すべてのCPUで必ず高速になる",
  ],
  "l7-design-idempotency-key": [
    "キーが一意ならrequest内容を紐づけなくても、同じキーを別の決済内容へ再利用して安全に実行できる",
    "決済処理の完了後にだけキーを保存すれば、処理完了と保存の間で障害が起きても二重決済を防げる",
    "同じキーへ同じHTTP responseを返すことが目的で、決済などbackendの副作用が重複しても問題ない",
    "サーバがrequest受信後に新しいキーを毎回発行すれば、clientが同じ操作を再送した場合も照合できる",
    "キーのTTLはclientの再試行可能期間より短くても、期限切れ後の再送を新規処理して二重実行にならない",
  ],
  "l7-design-sharding-strategy": [
    "単調増加キーのrange分割は新規書き込みを既存rangeへ均等配分するため、hotspotが起きにくい",
    "hash分割でも元キーの大小関係が配置順に保たれるため、連続range検索は単一shardで完結しやすい",
    "shard数を単純なhash値の剰余で増やしても既存データの配置は変わらず、再配置なしで拡張できる",
    "rangeかhashかを選べばreplication方式とconsistency levelも自動的に決まり、別途設計する必要はない",
    "主キーをhash分割すればsecondary indexも必ず同じshardへ収まり、scatter-gatherは発生しない",
  ],
  "l7-network-gossip-protocol": [
    "各roundで一定数のpeerへ送れば、指定時間内に全生存nodeへ必ず届く決定的broadcastとして扱える",
    "情報欠落を防ぐには各nodeが毎回全peerへ同時送信する必要があり、randomなfan-outは利用できない",
    "heartbeatをgossipすれば障害nodeを誤検知なく即座に判定でき、network遅延との区別も常に可能になる",
    "全nodeが最終的に同じ情報を持つ性質により、更新の合意順序とlinearizable readも同時に保証される",
    "peer選択はrandomでも通信は全node間の常時TCP接続が前提で、接続を都度作る実装は成立しない",
  ],
  "l7-network-cdn-origin-shield": [
    "全requestを必ずshield経由にすれば、edge cache hitでも経路が増えることなく常にlatencyを短縮できる",
    "shieldでcache hitしたresponseは利用者に最も近いedge hitと同じ距離なので、応答時間の差は生じない",
    "cache missを一拠点へ集約するだけで同一objectの同時requestも自動直列化され、request coalescingは不要になる",
    "shieldを単一regionへ固定するとその障害時も全edgeが自動でoriginへ到達するため、可用性設計は不要になる",
    "shieldはoriginのCache-Controlを無視して長期保存する層なので、private responseも安全に共有cacheできる",
  ],
  "l7-security-mtls": [
    "証明書でworkloadを認証できれば、その処理が利用者の意図した操作かというauthorizationも自動的に満たす",
    "proxyがclient証明書を検証した後は、外部から同名headerを注入できる構成でも転送された主体情報を信頼できる",
    "短命なclient証明書を使えば漏洩時の失効や緊急rotationは不要で、期限までの不正利用も防止できる",
    "private CAが署名した証明書ならSANや想定trust domainを検証せず、署名が正しい全clientを許可できる",
    "相互認証により通信のreplayや権限を持つserviceの誤代理も防げるため、application側の防御は不要になる",
  ],
  "l7-security-sandbox-escape": [
    "rootless containerで実行すれば共有kernelの脆弱性があっても、host側へ到達するescapeは成立しない",
    "seccompのdeny listで既知syscallを止めれば、filesystem mountやcapabilityなど他の境界は検討不要になる",
    "hardware VMへ隔離すればguestからhypervisorを攻撃する経路は消え、追加のpatch適用は不要になる",
    "filesystemをread-onlyにすればkernel syscallの脆弱性は悪用できず、processやnetworkへの脱出も防げる",
    "言語runtimeのsandbox内ならnative moduleやJITがpolicy外のmemoryへ触れても、隔離境界は維持される",
  ],
};

export function withSharperOptions(questions: readonly Question[]): Question[] {
  return questions.map((question) => {
    const overrides = sharperDistractors[question.id];
    const correctTexts = correctTextOverrides[question.id];

    if (!overrides && !correctTexts) {
      return question;
    }

    return {
      ...question,
      correct: correctTexts
        ? {
            ...question.correct,
            text: correctTexts.primary,
          }
        : question.correct,
      corrects: correctTexts
        ? [{ id: "correct-alt-1", text: correctTexts.alternate }]
        : question.corrects,
      distractors: question.distractors.map((distractor, index) => ({
        ...distractor,
        text: overrides?.[index] ?? distractor.text,
      })),
    };
  });
}
